'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' Your custom recording code should go in this file.
' The designer will only add methods to this file, so your custom code won't be overwritten.
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace StartAndLogin

    Public Partial Class Recording1

        ''' <summary>
        ''' This method gets called right after the recording has been started.
        ''' It can be used to execute recording specific initialization code.
        ''' </summary>
        Private Sub Init()
            ' Your recording specific initialization code goes here.
        End Sub

    End Class
End Namespace
