'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Drawing
Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace StartAndLogin
    ''' <summary>
    ''' The class representing the StartAndLoginRepository element repository.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3"), _
    RepositoryFolder("bd52a213-c438-436c-a532-238b176d01b5")> _
    Partial Public Class StartAndLoginRepository
        Inherits RepoGenBaseFolder

        Shared _instance As StartAndLoginRepository = New StartAndLoginRepository()
        Dim _start As StartAndLoginRepositoryFolders.StartAppFolder
        Dim _startmenuwindow As StartAndLoginRepositoryFolders.StartMenuWindowAppFolder
        Dim _dieseappkannnichtgeoeffnetwerden As StartAndLoginRepositoryFolders.DieseAppKannNichtGeoeffnetWerdenAppFolder
        Dim _explorer As StartAndLoginRepositoryFolders.ExplorerAppFolder
        Dim _explorer1 As StartAndLoginRepositoryFolders.Explorer1AppFolder
        Dim _skypefordesktop As StartAndLoginRepositoryFolders.SkypeForDesktopAppFolder
        Dim _explorer2 As StartAndLoginRepositoryFolders.Explorer2AppFolder

        ''' <summary>
        ''' Repository class constructor.
        ''' </summary>
        Public Sub New()
            MyBase.New("StartAndLoginRepository", "/", Nothing, 0, False,"bd52a213-c438-436c-a532-238b176d01b5", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
            _start = New StartAndLoginRepositoryFolders.StartAppFolder(Me)
            _startmenuwindow = New StartAndLoginRepositoryFolders.StartMenuWindowAppFolder(Me)
            _dieseappkannnichtgeoeffnetwerden = New StartAndLoginRepositoryFolders.DieseAppKannNichtGeoeffnetWerdenAppFolder(Me)
            _explorer = New StartAndLoginRepositoryFolders.ExplorerAppFolder(Me)
            _explorer1 = New StartAndLoginRepositoryFolders.Explorer1AppFolder(Me)
            _skypefordesktop = New StartAndLoginRepositoryFolders.SkypeForDesktopAppFolder(Me)
            _explorer2 = New StartAndLoginRepositoryFolders.Explorer2AppFolder(Me)
        End Sub

        ''' <summary>
        ''' Gets the singleton class instance representing the StartAndLoginRepository element repository.
        ''' </summary>
        <RepositoryFolder("bd52a213-c438-436c-a532-238b176d01b5")> _
        Public Shared ReadOnly Property Instance() As StartAndLoginRepository
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
#End Region

        ''' <summary>
        ''' The Self item info.
        ''' </summary>
        <RepositoryItemInfo("bd52a213-c438-436c-a532-238b176d01b5")> _
        Public Overridable ReadOnly Property SelfInfo() As RepoItemInfo
            Get
                Return _selfInfo
            End Get
        End Property

        ''' <summary>
        ''' The Start folder.
        ''' </summary>
        <RepositoryFolder("e74f4527-b9a7-4c6a-b7c3-55cf922b0a3b")> _
        Public Overridable ReadOnly Property Start As StartAndLoginRepositoryFolders.StartAppFolder
            Get
                Return _start
            End Get
        End Property

        ''' <summary>
        ''' The StartMenuWindow folder.
        ''' </summary>
        <RepositoryFolder("3d3de20e-20cb-4758-8044-f87f92639a07")> _
        Public Overridable ReadOnly Property StartMenuWindow As StartAndLoginRepositoryFolders.StartMenuWindowAppFolder
            Get
                Return _startmenuwindow
            End Get
        End Property

        ''' <summary>
        ''' The DieseAppKannNichtGeoeffnetWerden folder.
        ''' </summary>
        <RepositoryFolder("eb5738d0-e809-47c0-8ace-21f5d811338a")> _
        Public Overridable ReadOnly Property DieseAppKannNichtGeoeffnetWerden As StartAndLoginRepositoryFolders.DieseAppKannNichtGeoeffnetWerdenAppFolder
            Get
                Return _dieseappkannnichtgeoeffnetwerden
            End Get
        End Property

        ''' <summary>
        ''' The Explorer folder.
        ''' </summary>
        <RepositoryFolder("854ad7f2-c004-4cdc-99e4-337ebb8d5dae")> _
        Public Overridable ReadOnly Property Explorer As StartAndLoginRepositoryFolders.ExplorerAppFolder
            Get
                Return _explorer
            End Get
        End Property

        ''' <summary>
        ''' The Explorer1 folder.
        ''' </summary>
        <RepositoryFolder("f7512d30-1d4d-46c4-94d5-64384ac6202e")> _
        Public Overridable ReadOnly Property Explorer1 As StartAndLoginRepositoryFolders.Explorer1AppFolder
            Get
                Return _explorer1
            End Get
        End Property

        ''' <summary>
        ''' The SkypeForDesktop folder.
        ''' </summary>
        <RepositoryFolder("496f783f-0523-4e8f-af1d-9552e5e760c4")> _
        Public Overridable ReadOnly Property SkypeForDesktop As StartAndLoginRepositoryFolders.SkypeForDesktopAppFolder
            Get
                Return _skypefordesktop
            End Get
        End Property

        ''' <summary>
        ''' The Explorer2 folder.
        ''' </summary>
        <RepositoryFolder("eba14fa8-71c7-4509-b888-0d02e294a967")> _
        Public Overridable ReadOnly Property Explorer2 As StartAndLoginRepositoryFolders.Explorer2AppFolder
            Get
                Return _explorer2
            End Get
        End Property
    End Class

    ''' <summary>
    ''' Inner folder classes.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")> _
    Partial Public Class StartAndLoginRepositoryFolders

        ''' <summary>
        ''' The StartAppFolder folder.
        ''' </summary>
        <RepositoryFolder("e74f4527-b9a7-4c6a-b7c3-55cf922b0a3b")> _
        Partial Public Class StartAppFolder
            Inherits RepoGenBaseFolder

            Dim _startInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new Start  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("Start", "/list[@name='Start']", parentFolder, 30000, Nothing, True, "e74f4527-b9a7-4c6a-b7c3-55cf922b0a3b", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _startInfo = New RepoItemInfo(Me, "Start", "listitem[@name='Start']", 30000, Nothing, "7ab97245-3a21-4601-aafd-c4154e104246")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("e74f4527-b9a7-4c6a-b7c3-55cf922b0a3b")> _
            Public Overridable ReadOnly Property Self As Ranorex.List
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.List)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("e74f4527-b9a7-4c6a-b7c3-55cf922b0a3b")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The Start item.
            ''' </summary>
            <RepositoryItem("7ab97245-3a21-4601-aafd-c4154e104246")> _
            Public Overridable ReadOnly Property Start As Ranorex.ListItem
                Get
                    Return _startInfo.CreateAdapter(Of Ranorex.ListItem)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Start item info.
            ''' </summary>
            <RepositoryItemInfo("7ab97245-3a21-4601-aafd-c4154e104246")> _
            Public Overridable ReadOnly Property StartInfo As RepoItemInfo
                Get
                    Return _startInfo
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The StartMenuWindowAppFolder folder.
        ''' </summary>
        <RepositoryFolder("3d3de20e-20cb-4758-8044-f87f92639a07")> _
        Partial Public Class StartMenuWindowAppFolder
            Inherits RepoGenBaseFolder

            Dim _viewswitchbuttonInfo As RepoItemInfo
            Dim _logoInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new StartMenuWindow  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("StartMenuWindow", "/container[@automationid='Start menu window']", parentFolder, 30000, Nothing, True, "3d3de20e-20cb-4758-8044-f87f92639a07", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _viewswitchbuttonInfo = New RepoItemInfo(Me, "ViewSwitchButton", "container[@automationid='Root']/?/?/list[@automationid='GridRoot']/?/?/button[@automationid='ViewSwitchButton']", 30000, Nothing, "70f19ff9-f84f-4c1c-bc06-99367833834d")
                _logoInfo = New RepoItemInfo(Me, "Logo", "container[@automationid='Root']/?/?/list[@automationid='GridRoot']//listitem[@automationid='Microsoft.SkypeApp_kzf8qxf38zg5c!App']/picture[@automationid='Logo']", 30000, Nothing, "ff44274b-a22f-4672-9145-7698be29c506")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("3d3de20e-20cb-4758-8044-f87f92639a07")> _
            Public Overridable ReadOnly Property Self As Ranorex.Container
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.Container)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("3d3de20e-20cb-4758-8044-f87f92639a07")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The ViewSwitchButton item.
            ''' </summary>
            <RepositoryItem("70f19ff9-f84f-4c1c-bc06-99367833834d")> _
            Public Overridable ReadOnly Property ViewSwitchButton As Ranorex.Button
                Get
                    Return _viewswitchbuttonInfo.CreateAdapter(Of Ranorex.Button)(True)
                End Get
            End Property

            ''' <summary>
            ''' The ViewSwitchButton item info.
            ''' </summary>
            <RepositoryItemInfo("70f19ff9-f84f-4c1c-bc06-99367833834d")> _
            Public Overridable ReadOnly Property ViewSwitchButtonInfo As RepoItemInfo
                Get
                    Return _viewswitchbuttonInfo
                End Get
            End Property

            ''' <summary>
            ''' The Logo item.
            ''' </summary>
            <RepositoryItem("ff44274b-a22f-4672-9145-7698be29c506")> _
            Public Overridable ReadOnly Property Logo As Ranorex.Picture
                Get
                    Return _logoInfo.CreateAdapter(Of Ranorex.Picture)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Logo item info.
            ''' </summary>
            <RepositoryItemInfo("ff44274b-a22f-4672-9145-7698be29c506")> _
            Public Overridable ReadOnly Property LogoInfo As RepoItemInfo
                Get
                    Return _logoInfo
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The DieseAppKannNichtGeoeffnetWerdenAppFolder folder.
        ''' </summary>
        <RepositoryFolder("eb5738d0-e809-47c0-8ace-21f5d811338a")> _
        Partial Public Class DieseAppKannNichtGeoeffnetWerdenAppFolder
            Inherits RepoGenBaseFolder

            Dim _button0Info As RepoItemInfo

            ''' <summary>
            ''' Creates a new DieseAppKannNichtGeoeffnetWerden  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("DieseAppKannNichtGeoeffnetWerden", "/form[@title~'^Diese\ App\ kann\ nicht\ geöf']", parentFolder, 30000, Nothing, True, "eb5738d0-e809-47c0-8ace-21f5d811338a", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _button0Info = New RepoItemInfo(Me, "Button0", "?/?/toolbar[@automationid='ButtonBar']/button[@automationid='Button0']", 30000, Nothing, "63fdf08a-2ce3-42e6-87bd-a18e53df89e1")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("eb5738d0-e809-47c0-8ace-21f5d811338a")> _
            Public Overridable ReadOnly Property Self As Ranorex.Form
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.Form)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("eb5738d0-e809-47c0-8ace-21f5d811338a")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The Button0 item.
            ''' </summary>
            <RepositoryItem("63fdf08a-2ce3-42e6-87bd-a18e53df89e1")> _
            Public Overridable ReadOnly Property Button0 As Ranorex.Button
                Get
                    Return _button0Info.CreateAdapter(Of Ranorex.Button)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Button0 item info.
            ''' </summary>
            <RepositoryItemInfo("63fdf08a-2ce3-42e6-87bd-a18e53df89e1")> _
            Public Overridable ReadOnly Property Button0Info As RepoItemInfo
                Get
                    Return _button0Info
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The ExplorerAppFolder folder.
        ''' </summary>
        <RepositoryFolder("854ad7f2-c004-4cdc-99e4-337ebb8d5dae")> _
        Partial Public Class ExplorerAppFolder
            Inherits RepoGenBaseFolder

            Dim _startandloginranorexstudioInfo As RepoItemInfo
            Dim _explorerInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new Explorer  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, Nothing, True, "854ad7f2-c004-4cdc-99e4-337ebb8d5dae", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _startandloginranorexstudioInfo = New RepoItemInfo(Me, "StartAndLoginRanorexStudio", "container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[@accessiblename~'^StartAndLogin\ -\ Ranorex\ S']", 30000, Nothing, "c760e13c-055c-4313-b262-a3a680976625")
                _explorerInfo = New RepoItemInfo(Me, "Explorer", "container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[@accessiblename='Explorer']", 30000, Nothing, "3de7909c-2201-4ad1-a23e-4444ef71cd23")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("854ad7f2-c004-4cdc-99e4-337ebb8d5dae")> _
            Public Overridable ReadOnly Property Self As Ranorex.MenuBar
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.MenuBar)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("854ad7f2-c004-4cdc-99e4-337ebb8d5dae")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The StartAndLoginRanorexStudio item.
            ''' </summary>
            <RepositoryItem("c760e13c-055c-4313-b262-a3a680976625")> _
            Public Overridable ReadOnly Property StartAndLoginRanorexStudio As Ranorex.Button
                Get
                    Return _startandloginranorexstudioInfo.CreateAdapter(Of Ranorex.Button)(True)
                End Get
            End Property

            ''' <summary>
            ''' The StartAndLoginRanorexStudio item info.
            ''' </summary>
            <RepositoryItemInfo("c760e13c-055c-4313-b262-a3a680976625")> _
            Public Overridable ReadOnly Property StartAndLoginRanorexStudioInfo As RepoItemInfo
                Get
                    Return _startandloginranorexstudioInfo
                End Get
            End Property

            ''' <summary>
            ''' The Explorer item.
            ''' </summary>
            <RepositoryItem("3de7909c-2201-4ad1-a23e-4444ef71cd23")> _
            Public Overridable ReadOnly Property Explorer As Ranorex.Button
                Get
                    Return _explorerInfo.CreateAdapter(Of Ranorex.Button)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Explorer item info.
            ''' </summary>
            <RepositoryItemInfo("3de7909c-2201-4ad1-a23e-4444ef71cd23")> _
            Public Overridable ReadOnly Property ExplorerInfo As RepoItemInfo
                Get
                    Return _explorerInfo
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The Explorer1AppFolder folder.
        ''' </summary>
        <RepositoryFolder("f7512d30-1d4d-46c4-94d5-64384ac6202e")> _
        Partial Public Class Explorer1AppFolder
            Inherits RepoGenBaseFolder

            Dim _skypefordesktopInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new Explorer1  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("Explorer1", "/form[@processname='explorer' and @class='TaskListThumbnailWnd']", parentFolder, 30000, Nothing, True, "f7512d30-1d4d-46c4-94d5-64384ac6202e", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _skypefordesktopInfo = New RepoItemInfo(Me, "SkypeForDesktop", "?/?/listitem[@accessiblename='Skype for Desktop']", 30000, Nothing, "1bfb6ce7-4d90-466c-9614-f461a63c2059")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("f7512d30-1d4d-46c4-94d5-64384ac6202e")> _
            Public Overridable ReadOnly Property Self As Ranorex.Form
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.Form)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("f7512d30-1d4d-46c4-94d5-64384ac6202e")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The SkypeForDesktop item.
            ''' </summary>
            <RepositoryItem("1bfb6ce7-4d90-466c-9614-f461a63c2059")> _
            Public Overridable ReadOnly Property SkypeForDesktop As Ranorex.ListItem
                Get
                    Return _skypefordesktopInfo.CreateAdapter(Of Ranorex.ListItem)(True)
                End Get
            End Property

            ''' <summary>
            ''' The SkypeForDesktop item info.
            ''' </summary>
            <RepositoryItemInfo("1bfb6ce7-4d90-466c-9614-f461a63c2059")> _
            Public Overridable ReadOnly Property SkypeForDesktopInfo As RepoItemInfo
                Get
                    Return _skypefordesktopInfo
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The SkypeForDesktopAppFolder folder.
        ''' </summary>
        <RepositoryFolder("496f783f-0523-4e8f-af1d-9552e5e760c4")> _
        Partial Public Class SkypeForDesktopAppFolder
            Inherits RepoGenBaseFolder

            Dim _toolbar1001Info As RepoItemInfo
            Dim _uiimageInfo As RepoItemInfo
            Dim _systemitemnamedisplayInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new SkypeForDesktop  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("SkypeForDesktop", "/form[@title='Skype for Desktop']", parentFolder, 30000, Nothing, True, "496f783f-0523-4e8f-af1d-9552e5e760c4", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _toolbar1001Info = New RepoItemInfo(Me, "ToolBar1001", "element[@class='WorkerW']/?/?/element[@controlid='41477']//toolbar[@controlid='1001']", 30000, Nothing, "7f783ad2-fcf1-4123-90f4-2d0688566370")
                _uiimageInfo = New RepoItemInfo(Me, "UIImage", "element[@class='ShellTabWindowClass']//container[@caption='ShellView']/?/?/listitem[@automationid='3']/picture[@classname='UIImage']", 30000, Nothing, "4e370e1a-d1b8-4b10-bc62-08bc38d6fd97")
                _systemitemnamedisplayInfo = New RepoItemInfo(Me, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//container[@caption='ShellView']/?/?/listitem[@automationid='3']/text[@automationid='System.ItemNameDisplay']", 30000, Nothing, "c728f830-6ae5-4b1d-8ec3-7210ed0bf94c")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("496f783f-0523-4e8f-af1d-9552e5e760c4")> _
            Public Overridable ReadOnly Property Self As Ranorex.Form
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.Form)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("496f783f-0523-4e8f-af1d-9552e5e760c4")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The ToolBar1001 item.
            ''' </summary>
            <RepositoryItem("7f783ad2-fcf1-4123-90f4-2d0688566370")> _
            Public Overridable ReadOnly Property ToolBar1001 As Ranorex.ToolBar
                Get
                    Return _toolbar1001Info.CreateAdapter(Of Ranorex.ToolBar)(True)
                End Get
            End Property

            ''' <summary>
            ''' The ToolBar1001 item info.
            ''' </summary>
            <RepositoryItemInfo("7f783ad2-fcf1-4123-90f4-2d0688566370")> _
            Public Overridable ReadOnly Property ToolBar1001Info As RepoItemInfo
                Get
                    Return _toolbar1001Info
                End Get
            End Property

            ''' <summary>
            ''' The UIImage item.
            ''' </summary>
            <RepositoryItem("4e370e1a-d1b8-4b10-bc62-08bc38d6fd97")> _
            Public Overridable ReadOnly Property UIImage As Ranorex.Picture
                Get
                    Return _uiimageInfo.CreateAdapter(Of Ranorex.Picture)(True)
                End Get
            End Property

            ''' <summary>
            ''' The UIImage item info.
            ''' </summary>
            <RepositoryItemInfo("4e370e1a-d1b8-4b10-bc62-08bc38d6fd97")> _
            Public Overridable ReadOnly Property UIImageInfo As RepoItemInfo
                Get
                    Return _uiimageInfo
                End Get
            End Property

            ''' <summary>
            ''' The SystemItemNameDisplay item.
            ''' </summary>
            <RepositoryItem("c728f830-6ae5-4b1d-8ec3-7210ed0bf94c")> _
            Public Overridable ReadOnly Property SystemItemNameDisplay As Ranorex.Text
                Get
                    Return _systemitemnamedisplayInfo.CreateAdapter(Of Ranorex.Text)(True)
                End Get
            End Property

            ''' <summary>
            ''' The SystemItemNameDisplay item info.
            ''' </summary>
            <RepositoryItemInfo("c728f830-6ae5-4b1d-8ec3-7210ed0bf94c")> _
            Public Overridable ReadOnly Property SystemItemNameDisplayInfo As RepoItemInfo
                Get
                    Return _systemitemnamedisplayInfo
                End Get
            End Property
        End Class

        ''' <summary>
        ''' The Explorer2AppFolder folder.
        ''' </summary>
        <RepositoryFolder("eba14fa8-71c7-4509-b888-0d02e294a967")> _
        Partial Public Class Explorer2AppFolder
            Inherits RepoGenBaseFolder

            Dim _oeffnenInfo As RepoItemInfo

            ''' <summary>
            ''' Creates a new Explorer2  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("Explorer2", "/contextmenu[@processname='explorer']", parentFolder, 30000, Nothing, False, "eba14fa8-71c7-4509-b888-0d02e294a967", ".\RepositoryImages\StartAndLoginRepositorybd52a213.rximgres")
                _oeffnenInfo = New RepoItemInfo(Me, "OEffnen", "?/?/menuitem[@accessiblename='Öffnen']", 30000, Nothing, "b5aa5656-cd1c-4dfd-9d29-943c87ac0b59")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("eba14fa8-71c7-4509-b888-0d02e294a967")> _
            Public Overridable ReadOnly Property Self As Ranorex.ContextMenu
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.ContextMenu)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("eba14fa8-71c7-4509-b888-0d02e294a967")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The OEffnen item.
            ''' </summary>
            <RepositoryItem("b5aa5656-cd1c-4dfd-9d29-943c87ac0b59")> _
            Public Overridable ReadOnly Property OEffnen As Ranorex.MenuItem
                Get
                    Return _oeffnenInfo.CreateAdapter(Of Ranorex.MenuItem)(True)
                End Get
            End Property

            ''' <summary>
            ''' The OEffnen item info.
            ''' </summary>
            <RepositoryItemInfo("b5aa5656-cd1c-4dfd-9d29-943c87ac0b59")> _
            Public Overridable ReadOnly Property OEffnenInfo As RepoItemInfo
                Get
                    Return _oeffnenInfo
                End Get
            End Property
        End Class
    End Class
End Namespace
