'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace StartAndLogin
    ''' <summary>
    '''The StartSkype recording.
    ''' </summary>
    <TestModule("e484adff-2d91-4a77-a75f-dbaed2c92df5", ModuleType.Recording, 1)> _
    Partial Public Class StartSkype
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the StartAndLoginRepository repository.
        ''' </summary>
        Public Shared repo as StartAndLoginRepository = StartAndLoginRepository.Instance

        Shared _instance as StartSkype = new StartSkype()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As StartSkype
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 0
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 0.00

            Init()

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Explorer3.Skype' at 65;38.", repo.Explorer3.SkypeInfo, new RecordItemIndex(0))
            repo.Explorer3.Skype.DoubleClick("65;38")
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.AnmeldenOderErstellen' at 121;19.", repo.Skype.AnmeldenOderErstellenInfo, new RecordItemIndex(1))
            repo.Skype.AnmeldenOderErstellen.Click("121;19")
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.NamedContainerAutomationPeer' at 740;578.", repo.Skype.NamedContainerAutomationPeerInfo, new RecordItemIndex(2))
            repo.Skype.NamedContainerAutomationPeer.Click("740;578")
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test_automation_hsr@hotmail.com'.", new RecordItemIndex(3))
            Keyboard.Press("test_automation_hsr@hotmail.com")
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.NamedContainerAutomationPeer' at 1122;739.", repo.Skype.NamedContainerAutomationPeerInfo, new RecordItemIndex(4))
            repo.Skype.NamedContainerAutomationPeer.Click("1122;739")
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.NamedContainerAutomationPeer' at 712;585.", repo.Skype.NamedContainerAutomationPeerInfo, new RecordItemIndex(5))
            repo.Skype.NamedContainerAutomationPeer.Click("712;585")
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CASSoftwareTesting18'.", new RecordItemIndex(6))
            Keyboard.Press("CASSoftwareTesting18")
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.NamedContainerAutomationPeer' at 1170;746.", repo.Skype.NamedContainerAutomationPeerInfo, new RecordItemIndex(7))
            repo.Skype.NamedContainerAutomationPeer.Click("1170;746")
            
            Try
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)"+Chr(13)+""+Chr(10)+"Validating AttributeContains (Text>'Willkommen') on item 'Skype.WillkommenTest'.", repo.Skype.WillkommenTestInfo, new RecordItemIndex(8))
                Validate.AttributeContains(repo.Skype.WillkommenTestInfo, "Text", "Willkommen", Nothing, False)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(8))
            End Try

        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
