'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace StartAndLogin
    ''' <summary>
    '''The StartSkype recording.
    ''' </summary>
    <TestModule("e484adff-2d91-4a77-a75f-dbaed2c92df5", ModuleType.Recording, 1)> _
    Partial Public Class StartSkype
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the StartAndLoginRepository repository.
        ''' </summary>
        Public Shared repo as StartAndLoginRepository = StartAndLoginRepository.Instance

        Shared _instance as StartSkype = new StartSkype()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As StartSkype
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 100
            Delay.SpeedFactor = 1.00

            Init()

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.Explorer' at 38;15.", repo.Explorer.ExplorerInfo, new RecordItemIndex(0))
            repo.Explorer.Explorer.Click("38;15")
            Delay.Milliseconds(200)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.SkypeForDesktop' at 57;37.", repo.Explorer1.SkypeForDesktopInfo, new RecordItemIndex(1))
            repo.Explorer1.SkypeForDesktop.Click("57;37")
            Delay.Milliseconds(200)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SkypeForDesktop.ToolBar1001' at 531;5.", repo.SkypeForDesktop.ToolBar1001Info, new RecordItemIndex(2))
            repo.SkypeForDesktop.ToolBar1001.Click("531;5")
            Delay.Milliseconds(200)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3))
            Keyboard.Press("{Return}")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SkypeForDesktop.UIImage' at 9;11.", repo.SkypeForDesktop.UIImageInfo, new RecordItemIndex(4))
            repo.SkypeForDesktop.UIImage.DoubleClick("9;11")
            Delay.Milliseconds(200)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.StartAndLoginRanorexStudio' at 28;19.", repo.Explorer.StartAndLoginRanorexStudioInfo, new RecordItemIndex(5))
            repo.Explorer.StartAndLoginRanorexStudio.Click("28;19")
            Delay.Milliseconds(200)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
