///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EigenesProfilBearbeiten recording.
    /// </summary>
    [TestModule("628edbaf-f045-4d8a-b74f-9d5a079bd8dc", ModuleType.Recording, 1)]
    public partial class EigenesProfilBearbeiten : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static EigenesProfilBearbeiten instance = new EigenesProfilBearbeiten();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EigenesProfilBearbeiten()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EigenesProfilBearbeiten Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionen' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionenInfo, new RecordItemIndex(0));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionen.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.PopupMenu'.", repo.Skype.PopupMenu.SelfInfo, new RecordItemIndex(1));
            Validate.Exists(repo.Skype.PopupMenu.SelfInfo);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.PopupMenu.PopupItemEinstellungen'.", repo.Skype.PopupMenu.PopupItemEinstellungenInfo, new RecordItemIndex(3));
            Validate.Exists(repo.Skype.PopupMenu.PopupItemEinstellungenInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.PopupMenu.PopupItemEinstellungen' at Center.", repo.Skype.PopupMenu.PopupItemEinstellungenInfo, new RecordItemIndex(4));
            repo.Skype.PopupMenu.PopupItemEinstellungen.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen'.", repo.Skype.frmSkypeMain.frmEinstellungen.SelfInfo, new RecordItemIndex(5));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.SelfInfo);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitel'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitelInfo, new RecordItemIndex(6));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitelInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbild' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbildInfo, new RecordItemIndex(7));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbild.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmProfilbild'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmProfilbild.SelfInfo, new RecordItemIndex(8));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmProfilbild.SelfInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmProfilbild.btnZurueck' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmProfilbild.btnZurueckInfo, new RecordItemIndex(9));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmProfilbild.btnZurueck.Click();
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Angemeldet als') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAls'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAlsInfo, new RecordItemIndex(10));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAlsInfo, "Text", "Angemeldet als", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='test_automation_hsr@hotmail.com') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAls'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAlsInfo, new RecordItemIndex(11));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAlsInfo, "Text", "test_automation_hsr@hotmail.com", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Skype-Name') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeName'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeNameInfo, new RecordItemIndex(12));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeNameInfo, "Text", "Skype-Name", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='live:test_automation_hsr') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeName'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeNameInfo, new RecordItemIndex(13));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeNameInfo, "Text", "live:test_automation_hsr", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAllgemein' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAllgemeinInfo, new RecordItemIndex(14));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAllgemein.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitel'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitelInfo, new RecordItemIndex(15));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitelInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.btnSprache' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.btnSpracheInfo, new RecordItemIndex(16));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.btnSprache.Click();
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Gerätesprache - Device language') on item 'Skype.frmSkypeMain.frmEinstellungen.frmSprache.lblGeraetesprache'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmSprache.lblGeraetespracheInfo, new RecordItemIndex(17));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmSprache.lblGeraetespracheInfo, "Text", "Gerätesprache - Device language", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnDarstellung' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnDarstellungInfo, new RecordItemIndex(18));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnDarstellung.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.lbITitel'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.lbITitelInfo, new RecordItemIndex(19));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.lbITitelInfo);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnKlassisch'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnKlassischInfo, new RecordItemIndex(20));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnKlassischInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(20)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnBlau'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnBlauInfo, new RecordItemIndex(21));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnBlauInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(21)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsie'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsieInfo, new RecordItemIndex(22));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsieInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(22)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnMinze'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnMinzeInfo, new RecordItemIndex(23));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnMinzeInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(23)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnRosa'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnRosaInfo, new RecordItemIndex(24));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnRosaInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(24)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnGelb'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnGelbInfo, new RecordItemIndex(25));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnGelbInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(25)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbe'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbeInfo, new RecordItemIndex(26));
                Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbeInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(26)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsie' at 27;23.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsieInfo, new RecordItemIndex(27));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.btnFuchsie.Click("27;23");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbe'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbeInfo, new RecordItemIndex(28));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.cbVerifikationFarbeInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.optDunkel' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.optDunkelInfo, new RecordItemIndex(29));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmDarstellung.optDunkel.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAudioUndVideo' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAudioUndVideoInfo, new RecordItemIndex(30));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAudioUndVideo.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAnrufe' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAnrufeInfo, new RecordItemIndex(31));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnAnrufe.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnNachrichten' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnNachrichtenInfo, new RecordItemIndex(32));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnNachrichten.Click();
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Textgröße') on item 'Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblTextgroesse'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblTextgroesseInfo, new RecordItemIndex(33));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblTextgroesseInfo, "Text", "Textgröße", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(33)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Normal') on item 'Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblNormal'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblNormalInfo, new RecordItemIndex(34));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmNachrichten.lblNormalInfo, "Text", "Normal", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(34)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnBenachrichtigungen' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnBenachrichtigungenInfo, new RecordItemIndex(35));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnBenachrichtigungen.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Benachrichtigungstöne') on item 'Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.lblBenachrichtigungstoene'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.lblBenachrichtigungstoeneInfo, new RecordItemIndex(36));
            Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.lblBenachrichtigungstoeneInfo, "Text", "Benachrichtigungstöne");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.optBenachrichtigungstoeneDeaktivieren' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.optBenachrichtigungstoeneDeaktivierenInfo, new RecordItemIndex(37));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmBenachrichtigungen.optBenachrichtigungstoeneDeaktivieren.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnKontakte' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnKontakteInfo, new RecordItemIndex(38));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.btnKontakte.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmKontakte.btnSchliessen' at 7;6.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontakte.btnSchliessenInfo, new RecordItemIndex(39));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmKontakte.btnSchliessen.Click("7;6");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
