///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EigenesProfilBearbeiten recording.
    /// </summary>
    [TestModule("628edbaf-f045-4d8a-b74f-9d5a079bd8dc", ModuleType.Recording, 1)]
    public partial class EigenesProfilBearbeiten : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static EigenesProfilBearbeiten instance = new EigenesProfilBearbeiten();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EigenesProfilBearbeiten()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EigenesProfilBearbeiten Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionen' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionenInfo, new RecordItemIndex(0));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.btnOptionen.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.SelfInfo, new RecordItemIndex(1));
            repo.Skype.frmSkypeMain.frmEinstellungen.EinstellungenSideBar.Self.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitel'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitelInfo, new RecordItemIndex(2));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblTitelInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbild' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbildInfo, new RecordItemIndex(3));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.btnProfilbild.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.SelfInfo, new RecordItemIndex(4));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.Self.Click();
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='yourtext') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAls'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAlsInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblAngemeldetAlsInfo, "Text", "yourtext", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='yourtext') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAls'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAlsInfo, new RecordItemIndex(6));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtAngemeldetAlsInfo, "Text", "yourtext", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='yourtext') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeName'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeNameInfo, new RecordItemIndex(7));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.lblSkypeNameInfo, "Text", "yourtext", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='yourtext') on item 'Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeName'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeNameInfo, new RecordItemIndex(8));
                Validate.AttributeEqual(repo.Skype.frmSkypeMain.frmEinstellungen.frmKontoUndProfil.txtSkypeNameInfo, "Text", "yourtext", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmEinstellungen.frmAllgemein' at Center.", repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.SelfInfo, new RecordItemIndex(9));
            repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.Self.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitel'.", repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitelInfo, new RecordItemIndex(10));
            Validate.Exists(repo.Skype.frmSkypeMain.frmEinstellungen.frmAllgemein.lblTitelInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
