///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KontaktHinzufuegen recording.
    /// </summary>
    [TestModule("fbcedd80-444f-4a2c-aa01-ddc4e9f3f02e", ModuleType.Recording, 1)]
    public partial class KontaktHinzufuegen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static KontaktHinzufuegen instance = new KontaktHinzufuegen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KontaktHinzufuegen()
        {
            VornameUndName = "Hans Mueller";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KontaktHinzufuegen Instance
        {
            get { return instance; }
        }

#region Variables

        string _VornameUndName;

        /// <summary>
        /// Gets or sets the value of variable VornameUndName.
        /// </summary>
        [TestVariable("8a9aef5b-8d59-41ca-a2c0-9978215f7c68")]
        public string VornameUndName
        {
            get { return _VornameUndName; }
            set { _VornameUndName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.MainBar.btnKontakte' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.MainBar.btnKontakteInfo, new RecordItemIndex(0));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.MainBar.btnKontakte.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.btnKontaktHinzufuegen' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.btnKontaktHinzufuegenInfo, new RecordItemIndex(1));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.btnKontaktHinzufuegen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmKontaktHinzufuegen'.", repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.SelfInfo, new RecordItemIndex(2));
            Validate.Exists(repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmKontaktHinzufuegen.Detailbereich.ListItemTelefonnummerHinzufuegen' at Center.", repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.Detailbereich.ListItemTelefonnummerHinzufuegenInfo, new RecordItemIndex(3));
            repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.Detailbereich.ListItemTelefonnummerHinzufuegen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmTelefonnummerHinzufuegen'.", repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.SelfInfo, new RecordItemIndex(4));
            Validate.Exists(repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$VornameUndName' with focus on 'Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Detailbereich.txtVornameUndName'.", repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Detailbereich.txtVornameUndNameInfo, new RecordItemIndex(5));
            repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Detailbereich.txtVornameUndName.PressKeys(VornameUndName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Titelzeile.btnZurueck' at Center.", repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Titelzeile.btnZurueckInfo, new RecordItemIndex(6));
            repo.Skype.frmSkypeMain.frmTelefonnummerHinzufuegen.Titelzeile.btnZurueck.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmKontaktHinzufuegen.Titelzeile.btnSchliessen' at Center.", repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.Titelzeile.btnSchliessenInfo, new RecordItemIndex(7));
            repo.Skype.frmSkypeMain.frmKontaktHinzufuegen.Titelzeile.btnSchliessen.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
