///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("be8e16e1-b2fd-4987-9305-f6cab9d6a2e3", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            Username = "test_automation_hsr@hotmail.com";
            Passwort = "CASSoftwareTesting18";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("c301a966-2afa-4edb-a383-c13b1e73b0fd")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Passwort;

        /// <summary>
        /// Gets or sets the value of variable Passwort.
        /// </summary>
        [TestVariable("c9a4babc-9433-4fe2-89fc-08d4104e2081")]
        public string Passwort
        {
            get { return _Passwort; }
            set { _Passwort = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Vorname.
        /// </summary>
        [TestVariable("ca8b6c9f-adb8-4d94-8d82-75c3385a5a50")]
        public string Vorname
        {
            get { return repo.Vorname; }
            set { repo.Vorname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.btnAnmeldenOderErstellen' at 82;8.", repo.Skype.frmLogOnOff.btnAnmeldenOderErstellenInfo, new RecordItemIndex(0));
            repo.Skype.frmLogOnOff.btnAnmeldenOderErstellen.Click("82;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(1));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(2));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse.PressKeys(Username);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(4));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Passwort' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(5));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort.PressKeys(Passwort);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommen'.", repo.Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommenInfo, new RecordItemIndex(7));
                Validate.Exists(repo.Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommenInfo, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
