///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_SarahPfister recording.
    /// </summary>
    [TestModule("41f64bae-8a9f-419e-9108-17122424abd2", ModuleType.Recording, 1)]
    public partial class Login_SarahPfister : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static Login_SarahPfister instance = new Login_SarahPfister();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_SarahPfister()
        {
            Username = "test_automation_hsr2@hotmail.com";
            Passwort = "CASSoftwareTesting19";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_SarahPfister Instance
        {
            get { return instance; }
        }

#region Variables

        string _Username;

        /// <summary>
        /// Gets or sets the value of variable Username.
        /// </summary>
        [TestVariable("21a01815-62a6-473f-b38d-026eb4ea8248")]
        public string Username
        {
            get { return _Username; }
            set { _Username = value; }
        }

        string _Passwort;

        /// <summary>
        /// Gets or sets the value of variable Passwort.
        /// </summary>
        [TestVariable("0272f0f8-52bb-4740-ba14-e1cc87ffba09")]
        public string Passwort
        {
            get { return _Passwort; }
            set { _Passwort = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.btnAnmeldenOderErstellen' at 82;8.", repo.Skype.frmLogOnOff.btnAnmeldenOderErstellenInfo, new RecordItemIndex(0));
            repo.Skype.frmLogOnOff.btnAnmeldenOderErstellen.Click("82;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(1));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Username' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(2));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse.PressKeys(Username);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresseInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginEmailadresse);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(4));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Passwort' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(5));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort.PressKeys(Passwort);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginPasswort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswortInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginPasswort);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
