///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_TestAutomation recording.
    /// </summary>
    [TestModule("be8e16e1-b2fd-4987-9305-f6cab9d6a2e3", ModuleType.Recording, 1)]
    public partial class Login_TestAutomation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static Login_TestAutomation instance = new Login_TestAutomation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_TestAutomation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_TestAutomation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.btnAnmeldenOderErstellen' at 82;8.", repo.Skype.frmLogOnOff.btnAnmeldenOderErstellenInfo, new RecordItemIndex(0));
            repo.Skype.frmLogOnOff.btnAnmeldenOderErstellen.Click("82;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_EmailadresseInfo, new RecordItemIndex(1));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test_automation_hsr@hotmail.com' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_EmailadresseInfo, new RecordItemIndex(2));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse.PressKeys("test_automation_hsr@hotmail.com");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_EmailadresseInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Emailadresse);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort' at Center.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_PasswortInfo, new RecordItemIndex(4));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CASSoftwareTesting18' with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_PasswortInfo, new RecordItemIndex(5));
            repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort.PressKeys("CASSoftwareTesting18");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort'.", repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_PasswortInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.Skype.frmLogOnOff.frmLogOn.txtLoginfeld_Passwort);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>'Willkommen') on item 'Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommen'.", repo.Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommenInfo, new RecordItemIndex(7));
                Validate.AttributeContains(repo.Skype.frmSkypeMain.frmSkypeMainAreaRechts.txtWillkommenInfo, "Text", "Willkommen", null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
