///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TA_SkypeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
    public partial class TA_SkypeRepository : RepoGenBaseFolder
    {
        static TA_SkypeRepository instance = new TA_SkypeRepository();
        TA_SkypeRepositoryFolders.ExplorerAppFolder _explorer;
        TA_SkypeRepositoryFolders.SkypeAppFolder _skype;

        /// <summary>
        /// Gets the singleton class instance representing the TA_SkypeRepository element repository.
        /// </summary>
        [RepositoryFolder("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
        public static TA_SkypeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TA_SkypeRepository() 
            : base("TA_SkypeRepository", "/", null, 0, false, "bd9057c9-e431-44a7-ba05-6153dff61cc0", ".\\RepositoryImages\\TA_SkypeRepositorybd9057c9.rximgres")
        {
            _explorer = new TA_SkypeRepositoryFolders.ExplorerAppFolder(this);
            _skype = new TA_SkypeRepositoryFolders.SkypeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("4431fc6e-46f6-4e85-b084-435feecea8e6")]
        public virtual TA_SkypeRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Skype folder.
        /// </summary>
        [RepositoryFolder("f0a1d291-9d6e-4e9c-ac26-607165225622")]
        public virtual TA_SkypeRepositoryFolders.SkypeAppFolder Skype
        {
            get { return _skype; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class TA_SkypeRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("4431fc6e-46f6-4e85-b084-435feecea8e6")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _skypeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "4431fc6e-46f6-4e85-b084-435feecea8e6", "")
            {
                _skypeInfo = new RepoItemInfo(this, "Skype", "container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[@accessiblename='Skype']", 30000, null, "e9eb9817-e9f1-41a2-a062-16a50ef80794");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4431fc6e-46f6-4e85-b084-435feecea8e6")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4431fc6e-46f6-4e85-b084-435feecea8e6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Skype item.
            /// </summary>
            [RepositoryItem("e9eb9817-e9f1-41a2-a062-16a50ef80794")]
            public virtual Ranorex.Button Skype
            {
                get
                {
                    return _skypeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Skype item info.
            /// </summary>
            [RepositoryItemInfo("e9eb9817-e9f1-41a2-a062-16a50ef80794")]
            public virtual RepoItemInfo SkypeInfo
            {
                get
                {
                    return _skypeInfo;
                }
            }
        }

        /// <summary>
        /// The SkypeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0a1d291-9d6e-4e9c-ac26-607165225622")]
        public partial class SkypeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _anmeldenodererstellenInfo;
            RepoItemInfo _namedcontainerautomationpeerInfo;
            RepoItemInfo _willkommentestInfo;

            /// <summary>
            /// Creates a new Skype  folder.
            /// </summary>
            public SkypeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Skype", "/winapp[@appid='App' and @name='Skype' and @classname='Windows.UI.Core.CoreWindow' and @title='Skype' and @processname='SkypeApp' and @instance='0']", parentFolder, 30000, null, true, "f0a1d291-9d6e-4e9c-ac26-607165225622", "")
            {
                _anmeldenodererstellenInfo = new RepoItemInfo(this, "AnmeldenOderErstellen", "element[@orientation='None']/container[@orientation='None']/?/?/button[@name='Anmelden oder erstellen']//text[@name='Anmelden oder erstellen']", 30000, null, "86484711-50c6-4248-8edf-2f461ec41c45");
                _namedcontainerautomationpeerInfo = new RepoItemInfo(this, "NamedContainerAutomationPeer", "element[@orientation='None']//container[@classname='NamedContainerAutomationPeer']", 30000, null, "fcc4684b-c6fb-4463-ba41-3dbf99c93ac2");
                _willkommentestInfo = new RepoItemInfo(this, "WillkommenTest", "element/container[@orientation='None']/container[@orientation='None']/container[1]/container[2]/container[2]/?/?/text[@name='Willkommen, Test']", 30000, null, "e0c5c5a9-6bc3-4300-8e17-90883f25db01");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0a1d291-9d6e-4e9c-ac26-607165225622")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0a1d291-9d6e-4e9c-ac26-607165225622")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AnmeldenOderErstellen item.
            /// </summary>
            [RepositoryItem("86484711-50c6-4248-8edf-2f461ec41c45")]
            public virtual Ranorex.Text AnmeldenOderErstellen
            {
                get
                {
                    return _anmeldenodererstellenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AnmeldenOderErstellen item info.
            /// </summary>
            [RepositoryItemInfo("86484711-50c6-4248-8edf-2f461ec41c45")]
            public virtual RepoItemInfo AnmeldenOderErstellenInfo
            {
                get
                {
                    return _anmeldenodererstellenInfo;
                }
            }

            /// <summary>
            /// The NamedContainerAutomationPeer item.
            /// </summary>
            [RepositoryItem("fcc4684b-c6fb-4463-ba41-3dbf99c93ac2")]
            public virtual Ranorex.Container NamedContainerAutomationPeer
            {
                get
                {
                    return _namedcontainerautomationpeerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NamedContainerAutomationPeer item info.
            /// </summary>
            [RepositoryItemInfo("fcc4684b-c6fb-4463-ba41-3dbf99c93ac2")]
            public virtual RepoItemInfo NamedContainerAutomationPeerInfo
            {
                get
                {
                    return _namedcontainerautomationpeerInfo;
                }
            }

            /// <summary>
            /// The WillkommenTest item.
            /// </summary>
            [RepositoryItem("e0c5c5a9-6bc3-4300-8e17-90883f25db01")]
            public virtual Ranorex.Text WillkommenTest
            {
                get
                {
                    return _willkommentestInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WillkommenTest item info.
            /// </summary>
            [RepositoryItemInfo("e0c5c5a9-6bc3-4300-8e17-90883f25db01")]
            public virtual RepoItemInfo WillkommenTestInfo
            {
                get
                {
                    return _willkommentestInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}