///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TA_SkypeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
    public partial class TA_SkypeRepository : RepoGenBaseFolder
    {
        static TA_SkypeRepository instance = new TA_SkypeRepository();
        TA_SkypeRepositoryFolders.ExplorerAppFolder _explorer;
        TA_SkypeRepositoryFolders.SkypeAppFolder _skype;

        /// <summary>
        /// Gets the singleton class instance representing the TA_SkypeRepository element repository.
        /// </summary>
        [RepositoryFolder("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
        public static TA_SkypeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TA_SkypeRepository() 
            : base("TA_SkypeRepository", "/", null, 0, false, "bd9057c9-e431-44a7-ba05-6153dff61cc0", ".\\RepositoryImages\\TA_SkypeRepositorybd9057c9.rximgres")
        {
            _explorer = new TA_SkypeRepositoryFolders.ExplorerAppFolder(this);
            _skype = new TA_SkypeRepositoryFolders.SkypeAppFolder(this);
        }

#region Variables

        string _TelefonnummerTyp = "Privat";

        /// <summary>
        /// Gets or sets the value of variable TelefonnummerTyp.
        /// </summary>
        [TestVariable("cf945fe1-cbed-4d3b-84d6-91fc9e758dfa")]
        public string TelefonnummerTyp
        {
            get { return _TelefonnummerTyp; }
            set { _TelefonnummerTyp = value; }
        }

        string _Land = "";

        /// <summary>
        /// Gets or sets the value of variable Land.
        /// </summary>
        [TestVariable("bb7c91da-e47b-4ad4-ab9f-ff4139a43613")]
        public string Land
        {
            get { return _Land; }
            set { _Land = value; }
        }

        string _Landervorwahl = "";

        /// <summary>
        /// Gets or sets the value of variable Landervorwahl.
        /// </summary>
        [TestVariable("bc0eeed2-c9a5-46c9-b692-9f0d58dca290")]
        public string Landervorwahl
        {
            get { return _Landervorwahl; }
            set { _Landervorwahl = value; }
        }

        string _Laendervorwahl = "";

        /// <summary>
        /// Gets or sets the value of variable Laendervorwahl.
        /// </summary>
        [TestVariable("2475f7bf-414a-41e8-b6c0-309e6564c1a4")]
        public string Laendervorwahl
        {
            get { return _Laendervorwahl; }
            set { _Laendervorwahl = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bd9057c9-e431-44a7-ba05-6153dff61cc0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("4431fc6e-46f6-4e85-b084-435feecea8e6")]
        public virtual TA_SkypeRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Skype folder.
        /// </summary>
        [RepositoryFolder("f0a1d291-9d6e-4e9c-ac26-607165225622")]
        public virtual TA_SkypeRepositoryFolders.SkypeAppFolder Skype
        {
            get { return _skype; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class TA_SkypeRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("4431fc6e-46f6-4e85-b084-435feecea8e6")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _skypeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "4431fc6e-46f6-4e85-b084-435feecea8e6", "")
            {
                _skypeInfo = new RepoItemInfo(this, "Skype", "container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[@accessiblename='Skype']", 30000, null, "e9eb9817-e9f1-41a2-a062-16a50ef80794");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4431fc6e-46f6-4e85-b084-435feecea8e6")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4431fc6e-46f6-4e85-b084-435feecea8e6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Skype item.
            /// </summary>
            [RepositoryItem("e9eb9817-e9f1-41a2-a062-16a50ef80794")]
            public virtual Ranorex.Button Skype
            {
                get
                {
                    return _skypeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Skype item info.
            /// </summary>
            [RepositoryItemInfo("e9eb9817-e9f1-41a2-a062-16a50ef80794")]
            public virtual RepoItemInfo SkypeInfo
            {
                get
                {
                    return _skypeInfo;
                }
            }
        }

        /// <summary>
        /// The SkypeAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0a1d291-9d6e-4e9c-ac26-607165225622")]
        public partial class SkypeAppFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.FrmSkypeMainFolder _frmskypemain;
            TA_SkypeRepositoryFolders.FrmLaendervorwahlFolder _frmlaendervorwahl;
            TA_SkypeRepositoryFolders.None1Folder _none1;
            TA_SkypeRepositoryFolders.PopupMenuFolder _popupmenu;
            RepoItemInfo _btncloseInfo;
            RepoItemInfo _anmeldenodererstellenInfo;
            RepoItemInfo _namedcontainerautomationpeerInfo;

            /// <summary>
            /// Creates a new Skype  folder.
            /// </summary>
            public SkypeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Skype", "/winapp[@appid='App' and @name='Skype' and @processname='SkypeApp' and @instance='0']", parentFolder, 30000, null, true, "f0a1d291-9d6e-4e9c-ac26-607165225622", "")
            {
                _frmskypemain = new TA_SkypeRepositoryFolders.FrmSkypeMainFolder(this);
                _frmlaendervorwahl = new TA_SkypeRepositoryFolders.FrmLaendervorwahlFolder(this);
                _none1 = new TA_SkypeRepositoryFolders.None1Folder(this);
                _popupmenu = new TA_SkypeRepositoryFolders.PopupMenuFolder(this);
                _btncloseInfo = new RepoItemInfo(this, "btnClose", "titlebar[@name='Skype' and @classname='ApplicationFrameTitleBarWindow']/?/?/button[@automationid='Close']", 30000, null, "800e7cb4-3e1d-448f-ab90-44eab8d8a0fc");
                _anmeldenodererstellenInfo = new RepoItemInfo(this, "AnmeldenOderErstellen", "element[@orientation='None']/container[@orientation='None']/?/?/button[@name='Anmelden oder erstellen']//text[@name='Anmelden oder erstellen']", 30000, null, "86484711-50c6-4248-8edf-2f461ec41c45");
                _namedcontainerautomationpeerInfo = new RepoItemInfo(this, "NamedContainerAutomationPeer", "element[@orientation='None']//container[@classname='NamedContainerAutomationPeer']", 30000, null, "fcc4684b-c6fb-4463-ba41-3dbf99c93ac2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0a1d291-9d6e-4e9c-ac26-607165225622")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0a1d291-9d6e-4e9c-ac26-607165225622")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnClose item.
            /// </summary>
            [RepositoryItem("800e7cb4-3e1d-448f-ab90-44eab8d8a0fc")]
            public virtual Ranorex.Button btnClose
            {
                get
                {
                    return _btncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnClose item info.
            /// </summary>
            [RepositoryItemInfo("800e7cb4-3e1d-448f-ab90-44eab8d8a0fc")]
            public virtual RepoItemInfo btnCloseInfo
            {
                get
                {
                    return _btncloseInfo;
                }
            }

            /// <summary>
            /// The AnmeldenOderErstellen item.
            /// </summary>
            [RepositoryItem("86484711-50c6-4248-8edf-2f461ec41c45")]
            public virtual Ranorex.Text AnmeldenOderErstellen
            {
                get
                {
                    return _anmeldenodererstellenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AnmeldenOderErstellen item info.
            /// </summary>
            [RepositoryItemInfo("86484711-50c6-4248-8edf-2f461ec41c45")]
            public virtual RepoItemInfo AnmeldenOderErstellenInfo
            {
                get
                {
                    return _anmeldenodererstellenInfo;
                }
            }

            /// <summary>
            /// The NamedContainerAutomationPeer item.
            /// </summary>
            [RepositoryItem("fcc4684b-c6fb-4463-ba41-3dbf99c93ac2")]
            public virtual Ranorex.Container NamedContainerAutomationPeer
            {
                get
                {
                    return _namedcontainerautomationpeerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NamedContainerAutomationPeer item info.
            /// </summary>
            [RepositoryItemInfo("fcc4684b-c6fb-4463-ba41-3dbf99c93ac2")]
            public virtual RepoItemInfo NamedContainerAutomationPeerInfo
            {
                get
                {
                    return _namedcontainerautomationpeerInfo;
                }
            }

            /// <summary>
            /// The frmSkypeMain folder.
            /// </summary>
            [RepositoryFolder("5aa5a870-123d-4704-a329-534311aa601d")]
            public virtual TA_SkypeRepositoryFolders.FrmSkypeMainFolder frmSkypeMain
            {
                get { return _frmskypemain; }
            }

            /// <summary>
            /// The frmLaendervorwahl folder.
            /// </summary>
            [RepositoryFolder("601baf19-5e57-496d-80f6-7dd89fb4fd2e")]
            public virtual TA_SkypeRepositoryFolders.FrmLaendervorwahlFolder frmLaendervorwahl
            {
                get { return _frmlaendervorwahl; }
            }

            /// <summary>
            /// The None1 folder.
            /// </summary>
            [RepositoryFolder("62fa1213-ccc6-451a-9235-71d577eca75a")]
            public virtual TA_SkypeRepositoryFolders.None1Folder None1
            {
                get { return _none1; }
            }

            /// <summary>
            /// The PopupMenu folder.
            /// </summary>
            [RepositoryFolder("8805602d-800e-4666-b193-10151d283d95")]
            public virtual TA_SkypeRepositoryFolders.PopupMenuFolder PopupMenu
            {
                get { return _popupmenu; }
            }
        }

        /// <summary>
        /// The FrmSkypeMainFolder folder.
        /// </summary>
        [RepositoryFolder("5aa5a870-123d-4704-a329-534311aa601d")]
        public partial class FrmSkypeMainFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.FrmSkypeMainAreaLinksFolder _frmskypemainarealinks;
            TA_SkypeRepositoryFolders.FrmSkypeMainAreaRechtsFolder _frmskypemainarearechts;
            TA_SkypeRepositoryFolders.FrmEinstellungenFolder _frmeinstellungen;
            TA_SkypeRepositoryFolders.FrmKontaktHinzufuegenFolder _frmkontakthinzufuegen;
            TA_SkypeRepositoryFolders.FrmTelefonnummerHinzufuegenFolder _frmtelefonnummerhinzufuegen;

            /// <summary>
            /// Creates a new frmSkypeMain  folder.
            /// </summary>
            public FrmSkypeMainFolder(RepoGenBaseFolder parentFolder) :
                    base("frmSkypeMain", "element/container[@orientation='None']/?/container[@orientation='None']/container[1]/container[2]", parentFolder, 10000, null, false, "5aa5a870-123d-4704-a329-534311aa601d", "")
            {
                _frmskypemainarealinks = new TA_SkypeRepositoryFolders.FrmSkypeMainAreaLinksFolder(this);
                _frmskypemainarearechts = new TA_SkypeRepositoryFolders.FrmSkypeMainAreaRechtsFolder(this);
                _frmeinstellungen = new TA_SkypeRepositoryFolders.FrmEinstellungenFolder(this);
                _frmkontakthinzufuegen = new TA_SkypeRepositoryFolders.FrmKontaktHinzufuegenFolder(this);
                _frmtelefonnummerhinzufuegen = new TA_SkypeRepositoryFolders.FrmTelefonnummerHinzufuegenFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5aa5a870-123d-4704-a329-534311aa601d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5aa5a870-123d-4704-a329-534311aa601d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The frmSkypeMainAreaLinks folder.
            /// </summary>
            [RepositoryFolder("5c9c70bd-1d91-485a-93b2-08ea3a619272")]
            public virtual TA_SkypeRepositoryFolders.FrmSkypeMainAreaLinksFolder frmSkypeMainAreaLinks
            {
                get { return _frmskypemainarealinks; }
            }

            /// <summary>
            /// The frmSkypeMainAreaRechts folder.
            /// </summary>
            [RepositoryFolder("412b5203-a9e8-4a5f-a98e-4d28fe688301")]
            public virtual TA_SkypeRepositoryFolders.FrmSkypeMainAreaRechtsFolder frmSkypeMainAreaRechts
            {
                get { return _frmskypemainarearechts; }
            }

            /// <summary>
            /// The frmEinstellungen folder.
            /// </summary>
            [RepositoryFolder("7ccabb5d-56e8-429a-b556-2274bfd1ad25")]
            public virtual TA_SkypeRepositoryFolders.FrmEinstellungenFolder frmEinstellungen
            {
                get { return _frmeinstellungen; }
            }

            /// <summary>
            /// The frmKontaktHinzufuegen folder.
            /// </summary>
            [RepositoryFolder("8d5da8c9-94d8-434d-a729-46b7cfac64f4")]
            public virtual TA_SkypeRepositoryFolders.FrmKontaktHinzufuegenFolder frmKontaktHinzufuegen
            {
                get { return _frmkontakthinzufuegen; }
            }

            /// <summary>
            /// The frmTelefonnummerHinzufuegen folder.
            /// </summary>
            [RepositoryFolder("2f0a9e0f-3d65-4078-a666-d33c67eca43b")]
            public virtual TA_SkypeRepositoryFolders.FrmTelefonnummerHinzufuegenFolder frmTelefonnummerHinzufuegen
            {
                get { return _frmtelefonnummerhinzufuegen; }
            }
        }

        /// <summary>
        /// The FrmSkypeMainAreaLinksFolder folder.
        /// </summary>
        [RepositoryFolder("5c9c70bd-1d91-485a-93b2-08ea3a619272")]
        public partial class FrmSkypeMainAreaLinksFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.SucheFolder _suche;
            TA_SkypeRepositoryFolders.MainBarFolder _mainbar;
            TA_SkypeRepositoryFolders.DetailbereichFolder _detailbereich;
            RepoItemInfo _btnprofilInfo;
            RepoItemInfo _btnoptionenInfo;

            /// <summary>
            /// Creates a new frmSkypeMainAreaLinks  folder.
            /// </summary>
            public FrmSkypeMainAreaLinksFolder(RepoGenBaseFolder parentFolder) :
                    base("frmSkypeMainAreaLinks", "container[1]", parentFolder, 10000, null, false, "5c9c70bd-1d91-485a-93b2-08ea3a619272", "")
            {
                _suche = new TA_SkypeRepositoryFolders.SucheFolder(this);
                _mainbar = new TA_SkypeRepositoryFolders.MainBarFolder(this);
                _detailbereich = new TA_SkypeRepositoryFolders.DetailbereichFolder(this);
                _btnprofilInfo = new RepoItemInfo(this, "btnProfil", "button[@name='Meine Info, Aktiv']", 10000, null, "ac746c6c-56ae-4781-90b8-29adf1473341");
                _btnoptionenInfo = new RepoItemInfo(this, "btnOptionen", "button[@name='Weitere Optionen']", 10000, null, "0454c710-8615-4339-9ee4-a76964f09952");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c9c70bd-1d91-485a-93b2-08ea3a619272")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c9c70bd-1d91-485a-93b2-08ea3a619272")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnProfil item.
            /// </summary>
            [RepositoryItem("ac746c6c-56ae-4781-90b8-29adf1473341")]
            public virtual Ranorex.Button btnProfil
            {
                get
                {
                    return _btnprofilInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnProfil item info.
            /// </summary>
            [RepositoryItemInfo("ac746c6c-56ae-4781-90b8-29adf1473341")]
            public virtual RepoItemInfo btnProfilInfo
            {
                get
                {
                    return _btnprofilInfo;
                }
            }

            /// <summary>
            /// The btnOptionen item.
            /// </summary>
            [RepositoryItem("0454c710-8615-4339-9ee4-a76964f09952")]
            public virtual Ranorex.Button btnOptionen
            {
                get
                {
                    return _btnoptionenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOptionen item info.
            /// </summary>
            [RepositoryItemInfo("0454c710-8615-4339-9ee4-a76964f09952")]
            public virtual RepoItemInfo btnOptionenInfo
            {
                get
                {
                    return _btnoptionenInfo;
                }
            }

            /// <summary>
            /// The Suche folder.
            /// </summary>
            [RepositoryFolder("ad6f7a66-8371-4a7d-a830-c06b18a8d02b")]
            public virtual TA_SkypeRepositoryFolders.SucheFolder Suche
            {
                get { return _suche; }
            }

            /// <summary>
            /// The MainBar folder.
            /// </summary>
            [RepositoryFolder("d46f09db-2e81-4265-b5bd-4f82e1c7e37f")]
            public virtual TA_SkypeRepositoryFolders.MainBarFolder MainBar
            {
                get { return _mainbar; }
            }

            /// <summary>
            /// The Detailbereich folder.
            /// </summary>
            [RepositoryFolder("5735fb83-eb90-491d-9581-9d117dc21cd5")]
            public virtual TA_SkypeRepositoryFolders.DetailbereichFolder Detailbereich
            {
                get { return _detailbereich; }
            }
        }

        /// <summary>
        /// The SucheFolder folder.
        /// </summary>
        [RepositoryFolder("ad6f7a66-8371-4a7d-a830-c06b18a8d02b")]
        public partial class SucheFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Suche  folder.
            /// </summary>
            public SucheFolder(RepoGenBaseFolder parentFolder) :
                    base("Suche", "container[1]", parentFolder, 10000, null, false, "ad6f7a66-8371-4a7d-a830-c06b18a8d02b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ad6f7a66-8371-4a7d-a830-c06b18a8d02b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ad6f7a66-8371-4a7d-a830-c06b18a8d02b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The MainBarFolder folder.
        /// </summary>
        [RepositoryFolder("d46f09db-2e81-4265-b5bd-4f82e1c7e37f")]
        public partial class MainBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnchatsInfo;
            RepoItemInfo _btnanrufeInfo;
            RepoItemInfo _btnkontakteInfo;
            RepoItemInfo _btnbenachrichtigungenInfo;

            /// <summary>
            /// Creates a new MainBar  folder.
            /// </summary>
            public MainBarFolder(RepoGenBaseFolder parentFolder) :
                    base("MainBar", "container[2]", parentFolder, 10000, null, false, "d46f09db-2e81-4265-b5bd-4f82e1c7e37f", "")
            {
                _btnchatsInfo = new RepoItemInfo(this, "btnChats", "button[1]", 10000, null, "8a080763-543f-4881-8e59-43f755dd6809");
                _btnanrufeInfo = new RepoItemInfo(this, "btnAnrufe", "button[2]", 10000, null, "a05cd0ed-9d6a-406e-87db-45679143f2e1");
                _btnkontakteInfo = new RepoItemInfo(this, "btnKontakte", "button[3]", 10000, null, "5ebbd5d5-b170-4cdf-8c3a-d51216c01caa");
                _btnbenachrichtigungenInfo = new RepoItemInfo(this, "btnBenachrichtigungen", "button[4]", 10000, null, "454a3072-f5de-436d-b4d8-bb558fde03e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d46f09db-2e81-4265-b5bd-4f82e1c7e37f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d46f09db-2e81-4265-b5bd-4f82e1c7e37f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnChats item.
            /// </summary>
            [RepositoryItem("8a080763-543f-4881-8e59-43f755dd6809")]
            public virtual Ranorex.Button btnChats
            {
                get
                {
                    return _btnchatsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnChats item info.
            /// </summary>
            [RepositoryItemInfo("8a080763-543f-4881-8e59-43f755dd6809")]
            public virtual RepoItemInfo btnChatsInfo
            {
                get
                {
                    return _btnchatsInfo;
                }
            }

            /// <summary>
            /// The btnAnrufe item.
            /// </summary>
            [RepositoryItem("a05cd0ed-9d6a-406e-87db-45679143f2e1")]
            public virtual Ranorex.Button btnAnrufe
            {
                get
                {
                    return _btnanrufeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAnrufe item info.
            /// </summary>
            [RepositoryItemInfo("a05cd0ed-9d6a-406e-87db-45679143f2e1")]
            public virtual RepoItemInfo btnAnrufeInfo
            {
                get
                {
                    return _btnanrufeInfo;
                }
            }

            /// <summary>
            /// The btnKontakte item.
            /// </summary>
            [RepositoryItem("5ebbd5d5-b170-4cdf-8c3a-d51216c01caa")]
            public virtual Ranorex.Button btnKontakte
            {
                get
                {
                    return _btnkontakteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnKontakte item info.
            /// </summary>
            [RepositoryItemInfo("5ebbd5d5-b170-4cdf-8c3a-d51216c01caa")]
            public virtual RepoItemInfo btnKontakteInfo
            {
                get
                {
                    return _btnkontakteInfo;
                }
            }

            /// <summary>
            /// The btnBenachrichtigungen item.
            /// </summary>
            [RepositoryItem("454a3072-f5de-436d-b4d8-bb558fde03e5")]
            public virtual Ranorex.Button btnBenachrichtigungen
            {
                get
                {
                    return _btnbenachrichtigungenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnBenachrichtigungen item info.
            /// </summary>
            [RepositoryItemInfo("454a3072-f5de-436d-b4d8-bb558fde03e5")]
            public virtual RepoItemInfo btnBenachrichtigungenInfo
            {
                get
                {
                    return _btnbenachrichtigungenInfo;
                }
            }
        }

        /// <summary>
        /// The DetailbereichFolder folder.
        /// </summary>
        [RepositoryFolder("5735fb83-eb90-491d-9581-9d117dc21cd5")]
        public partial class DetailbereichFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnkontakthinzufuegenInfo;

            /// <summary>
            /// Creates a new Detailbereich  folder.
            /// </summary>
            public DetailbereichFolder(RepoGenBaseFolder parentFolder) :
                    base("Detailbereich", "container[3]", parentFolder, 10000, null, false, "5735fb83-eb90-491d-9581-9d117dc21cd5", "")
            {
                _btnkontakthinzufuegenInfo = new RepoItemInfo(this, "btnKontaktHinzufuegen", "button[@name='Neuen Kontakt hinzufügen']", 30000, null, "8eb3a25b-f19e-4644-b0cd-3396ceea227a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5735fb83-eb90-491d-9581-9d117dc21cd5")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5735fb83-eb90-491d-9581-9d117dc21cd5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnKontaktHinzufuegen item.
            /// </summary>
            [RepositoryItem("8eb3a25b-f19e-4644-b0cd-3396ceea227a")]
            public virtual Ranorex.Button btnKontaktHinzufuegen
            {
                get
                {
                    return _btnkontakthinzufuegenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnKontaktHinzufuegen item info.
            /// </summary>
            [RepositoryItemInfo("8eb3a25b-f19e-4644-b0cd-3396ceea227a")]
            public virtual RepoItemInfo btnKontaktHinzufuegenInfo
            {
                get
                {
                    return _btnkontakthinzufuegenInfo;
                }
            }
        }

        /// <summary>
        /// The FrmSkypeMainAreaRechtsFolder folder.
        /// </summary>
        [RepositoryFolder("412b5203-a9e8-4a5f-a98e-4d28fe688301")]
        public partial class FrmSkypeMainAreaRechtsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtwillkommenInfo;

            /// <summary>
            /// Creates a new frmSkypeMainAreaRechts  folder.
            /// </summary>
            public FrmSkypeMainAreaRechtsFolder(RepoGenBaseFolder parentFolder) :
                    base("frmSkypeMainAreaRechts", "container[2]", parentFolder, 10000, null, false, "412b5203-a9e8-4a5f-a98e-4d28fe688301", "")
            {
                _txtwillkommenInfo = new RepoItemInfo(this, "txtWillkommen", "?/?/text[@name='Willkommen, Test']", 30000, null, "e0c5c5a9-6bc3-4300-8e17-90883f25db01");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("412b5203-a9e8-4a5f-a98e-4d28fe688301")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("412b5203-a9e8-4a5f-a98e-4d28fe688301")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtWillkommen item.
            /// </summary>
            [RepositoryItem("e0c5c5a9-6bc3-4300-8e17-90883f25db01")]
            public virtual Ranorex.Text txtWillkommen
            {
                get
                {
                    return _txtwillkommenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtWillkommen item info.
            /// </summary>
            [RepositoryItemInfo("e0c5c5a9-6bc3-4300-8e17-90883f25db01")]
            public virtual RepoItemInfo txtWillkommenInfo
            {
                get
                {
                    return _txtwillkommenInfo;
                }
            }
        }

        /// <summary>
        /// The FrmEinstellungenFolder folder.
        /// </summary>
        [RepositoryFolder("7ccabb5d-56e8-429a-b556-2274bfd1ad25")]
        public partial class FrmEinstellungenFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.EinstellungenSideBarFolder _einstellungensidebar;
            TA_SkypeRepositoryFolders.FrmKontoUndProfilFolder _frmkontoundprofil;
            TA_SkypeRepositoryFolders.FrmAllgemeinFolder _frmallgemein;

            /// <summary>
            /// Creates a new frmEinstellungen  folder.
            /// </summary>
            public FrmEinstellungenFolder(RepoGenBaseFolder parentFolder) :
                    base("frmEinstellungen", "container[6]", parentFolder, 10000, null, false, "7ccabb5d-56e8-429a-b556-2274bfd1ad25", "")
            {
                _einstellungensidebar = new TA_SkypeRepositoryFolders.EinstellungenSideBarFolder(this);
                _frmkontoundprofil = new TA_SkypeRepositoryFolders.FrmKontoUndProfilFolder(this);
                _frmallgemein = new TA_SkypeRepositoryFolders.FrmAllgemeinFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ccabb5d-56e8-429a-b556-2274bfd1ad25")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ccabb5d-56e8-429a-b556-2274bfd1ad25")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EinstellungenSideBar folder.
            /// </summary>
            [RepositoryFolder("1fc62bd2-8a5c-438d-86c7-42368263ecf8")]
            public virtual TA_SkypeRepositoryFolders.EinstellungenSideBarFolder EinstellungenSideBar
            {
                get { return _einstellungensidebar; }
            }

            /// <summary>
            /// The frmKontoUndProfil folder.
            /// </summary>
            [RepositoryFolder("5f9d0857-bd8e-4df9-a59c-5dc6d770b547")]
            public virtual TA_SkypeRepositoryFolders.FrmKontoUndProfilFolder frmKontoUndProfil
            {
                get { return _frmkontoundprofil; }
            }

            /// <summary>
            /// The frmAllgemein folder.
            /// </summary>
            [RepositoryFolder("70ed95df-47f7-4461-86e8-4a9ff982d86a")]
            public virtual TA_SkypeRepositoryFolders.FrmAllgemeinFolder frmAllgemein
            {
                get { return _frmallgemein; }
            }
        }

        /// <summary>
        /// The EinstellungenSideBarFolder folder.
        /// </summary>
        [RepositoryFolder("1fc62bd2-8a5c-438d-86c7-42368263ecf8")]
        public partial class EinstellungenSideBarFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new EinstellungenSideBar  folder.
            /// </summary>
            public EinstellungenSideBarFolder(RepoGenBaseFolder parentFolder) :
                    base("EinstellungenSideBar", "container[@name='Konto & Profil']/container[1]", parentFolder, 10000, null, false, "1fc62bd2-8a5c-438d-86c7-42368263ecf8", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1fc62bd2-8a5c-438d-86c7-42368263ecf8")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1fc62bd2-8a5c-438d-86c7-42368263ecf8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FrmKontoUndProfilFolder folder.
        /// </summary>
        [RepositoryFolder("5f9d0857-bd8e-4df9-a59c-5dc6d770b547")]
        public partial class FrmKontoUndProfilFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnprofilbildInfo;
            RepoItemInfo _lblangemeldetalsInfo;
            RepoItemInfo _txtangemeldetalsInfo;
            RepoItemInfo _lblskypenameInfo;
            RepoItemInfo _txtskypenameInfo;
            RepoItemInfo _lbltitelInfo;

            /// <summary>
            /// Creates a new frmKontoUndProfil  folder.
            /// </summary>
            public FrmKontoUndProfilFolder(RepoGenBaseFolder parentFolder) :
                    base("frmKontoUndProfil", "container[@name='Konto & Profil']/container[@classname='ScrollViewer']", parentFolder, 10000, null, false, "5f9d0857-bd8e-4df9-a59c-5dc6d770b547", "")
            {
                _btnprofilbildInfo = new RepoItemInfo(this, "btnProfilbild", "container/container[1]/button[@name='Profilbild']", 10000, null, "cc141fb3-b234-462c-b963-573b39eecbb7");
                _lblangemeldetalsInfo = new RepoItemInfo(this, "lblAngemeldetAls", "container/container[2]/button[@name~'^Angemeldet\\ als,\\ test_auto']/?/?/text[@name='Angemeldet als']", 10000, null, "ab63f76c-9ce1-466c-8ed1-240b7d6aef70");
                _txtangemeldetalsInfo = new RepoItemInfo(this, "txtAngemeldetAls", "container/container[2]/button[@name~'^Angemeldet\\ als,\\ test_auto']/?/?/container[@orientation='None']/text[@name~'^test_automation_hsr@hotma']", 10000, null, "60361f35-ecc5-49fd-964a-7111de14a5ee");
                _lblskypenameInfo = new RepoItemInfo(this, "lblSkypeName", "container/container[3]/button[@name~'^Skype-Name,\\ live:test_aut']/?/?/text[@name='Skype-Name']", 10000, null, "340e4ffd-74a6-46b3-89d5-310b9adee755");
                _txtskypenameInfo = new RepoItemInfo(this, "txtSkypeName", "container/container[3]/button[@name~'^Skype-Name,\\ live:test_aut']/?/?/container[@orientation='None']/text[@name='live:test_automation_hsr']", 10000, null, "9793f053-f480-46a2-b093-ae6b2bd4bef9");
                _lbltitelInfo = new RepoItemInfo(this, "lblTitel", "?/?/text[@name='DEIN SKYPE-PROFIL']", 10000, null, "3e1d50eb-633f-40e4-a124-441fafaa5644");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f9d0857-bd8e-4df9-a59c-5dc6d770b547")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f9d0857-bd8e-4df9-a59c-5dc6d770b547")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnProfilbild item.
            /// </summary>
            [RepositoryItem("cc141fb3-b234-462c-b963-573b39eecbb7")]
            public virtual Ranorex.Button btnProfilbild
            {
                get
                {
                    return _btnprofilbildInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnProfilbild item info.
            /// </summary>
            [RepositoryItemInfo("cc141fb3-b234-462c-b963-573b39eecbb7")]
            public virtual RepoItemInfo btnProfilbildInfo
            {
                get
                {
                    return _btnprofilbildInfo;
                }
            }

            /// <summary>
            /// The lblAngemeldetAls item.
            /// </summary>
            [RepositoryItem("ab63f76c-9ce1-466c-8ed1-240b7d6aef70")]
            public virtual Ranorex.Text lblAngemeldetAls
            {
                get
                {
                    return _lblangemeldetalsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblAngemeldetAls item info.
            /// </summary>
            [RepositoryItemInfo("ab63f76c-9ce1-466c-8ed1-240b7d6aef70")]
            public virtual RepoItemInfo lblAngemeldetAlsInfo
            {
                get
                {
                    return _lblangemeldetalsInfo;
                }
            }

            /// <summary>
            /// The txtAngemeldetAls item.
            /// </summary>
            [RepositoryItem("60361f35-ecc5-49fd-964a-7111de14a5ee")]
            public virtual Ranorex.Text txtAngemeldetAls
            {
                get
                {
                    return _txtangemeldetalsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtAngemeldetAls item info.
            /// </summary>
            [RepositoryItemInfo("60361f35-ecc5-49fd-964a-7111de14a5ee")]
            public virtual RepoItemInfo txtAngemeldetAlsInfo
            {
                get
                {
                    return _txtangemeldetalsInfo;
                }
            }

            /// <summary>
            /// The lblSkypeName item.
            /// </summary>
            [RepositoryItem("340e4ffd-74a6-46b3-89d5-310b9adee755")]
            public virtual Ranorex.Text lblSkypeName
            {
                get
                {
                    return _lblskypenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblSkypeName item info.
            /// </summary>
            [RepositoryItemInfo("340e4ffd-74a6-46b3-89d5-310b9adee755")]
            public virtual RepoItemInfo lblSkypeNameInfo
            {
                get
                {
                    return _lblskypenameInfo;
                }
            }

            /// <summary>
            /// The txtSkypeName item.
            /// </summary>
            [RepositoryItem("9793f053-f480-46a2-b093-ae6b2bd4bef9")]
            public virtual Ranorex.Text txtSkypeName
            {
                get
                {
                    return _txtskypenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSkypeName item info.
            /// </summary>
            [RepositoryItemInfo("9793f053-f480-46a2-b093-ae6b2bd4bef9")]
            public virtual RepoItemInfo txtSkypeNameInfo
            {
                get
                {
                    return _txtskypenameInfo;
                }
            }

            /// <summary>
            /// The lblTitel item.
            /// </summary>
            [RepositoryItem("3e1d50eb-633f-40e4-a124-441fafaa5644")]
            public virtual Ranorex.Text lblTitel
            {
                get
                {
                    return _lbltitelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblTitel item info.
            /// </summary>
            [RepositoryItemInfo("3e1d50eb-633f-40e4-a124-441fafaa5644")]
            public virtual RepoItemInfo lblTitelInfo
            {
                get
                {
                    return _lbltitelInfo;
                }
            }
        }

        /// <summary>
        /// The FrmAllgemeinFolder folder.
        /// </summary>
        [RepositoryFolder("70ed95df-47f7-4461-86e8-4a9ff982d86a")]
        public partial class FrmAllgemeinFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lbltitelInfo;
            RepoItemInfo _btnspracheInfo;
            RepoItemInfo _btnstandortmitbingteilenausInfo;

            /// <summary>
            /// Creates a new frmAllgemein  folder.
            /// </summary>
            public FrmAllgemeinFolder(RepoGenBaseFolder parentFolder) :
                    base("frmAllgemein", "container[@name='Allgemein']/container[@classname='ScrollViewer']", parentFolder, 10000, null, false, "70ed95df-47f7-4461-86e8-4a9ff982d86a", "")
            {
                _lbltitelInfo = new RepoItemInfo(this, "lblTitel", "?/?/text[@name='ALLGEMEIN']", 10000, null, "b2ee7b14-95bf-48eb-98c8-1b92205830ee");
                _btnspracheInfo = new RepoItemInfo(this, "btnSprache", "container/container[@orientation='None']/button[@name='Sprache']", 10000, null, "5195c865-9032-4094-98ba-a0bccfbab17e");
                _btnstandortmitbingteilenausInfo = new RepoItemInfo(this, "BtnStandortMitBingTeilenAus", "?/?/button[@name~'^Standort\\ mit\\ Bing\\ teilen,']", 10000, null, "0bd2e3f6-dbb9-4919-ba4a-bfc1a5ef9166");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70ed95df-47f7-4461-86e8-4a9ff982d86a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70ed95df-47f7-4461-86e8-4a9ff982d86a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lblTitel item.
            /// </summary>
            [RepositoryItem("b2ee7b14-95bf-48eb-98c8-1b92205830ee")]
            public virtual Ranorex.Text lblTitel
            {
                get
                {
                    return _lbltitelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblTitel item info.
            /// </summary>
            [RepositoryItemInfo("b2ee7b14-95bf-48eb-98c8-1b92205830ee")]
            public virtual RepoItemInfo lblTitelInfo
            {
                get
                {
                    return _lbltitelInfo;
                }
            }

            /// <summary>
            /// The btnSprache item.
            /// </summary>
            [RepositoryItem("5195c865-9032-4094-98ba-a0bccfbab17e")]
            public virtual Ranorex.Button btnSprache
            {
                get
                {
                    return _btnspracheInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSprache item info.
            /// </summary>
            [RepositoryItemInfo("5195c865-9032-4094-98ba-a0bccfbab17e")]
            public virtual RepoItemInfo btnSpracheInfo
            {
                get
                {
                    return _btnspracheInfo;
                }
            }

            /// <summary>
            /// The BtnStandortMitBingTeilenAus item.
            /// </summary>
            [RepositoryItem("0bd2e3f6-dbb9-4919-ba4a-bfc1a5ef9166")]
            public virtual Ranorex.Button BtnStandortMitBingTeilenAus
            {
                get
                {
                    return _btnstandortmitbingteilenausInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnStandortMitBingTeilenAus item info.
            /// </summary>
            [RepositoryItemInfo("0bd2e3f6-dbb9-4919-ba4a-bfc1a5ef9166")]
            public virtual RepoItemInfo BtnStandortMitBingTeilenAusInfo
            {
                get
                {
                    return _btnstandortmitbingteilenausInfo;
                }
            }
        }

        /// <summary>
        /// The FrmKontaktHinzufuegenFolder folder.
        /// </summary>
        [RepositoryFolder("8d5da8c9-94d8-434d-a729-46b7cfac64f4")]
        public partial class FrmKontaktHinzufuegenFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.TitelzeileFolder _titelzeile;
            TA_SkypeRepositoryFolders.KontaktsucheFolder _kontaktsuche;
            TA_SkypeRepositoryFolders.DetailbereichFolder1 _detailbereich;

            /// <summary>
            /// Creates a new frmKontaktHinzufuegen  folder.
            /// </summary>
            public FrmKontaktHinzufuegenFolder(RepoGenBaseFolder parentFolder) :
                    base("frmKontaktHinzufuegen", "container[6]/container[@name='Neuen Kontakt hinzufügen']/container[@orientation='None']", parentFolder, 30000, null, false, "8d5da8c9-94d8-434d-a729-46b7cfac64f4", "")
            {
                _titelzeile = new TA_SkypeRepositoryFolders.TitelzeileFolder(this);
                _kontaktsuche = new TA_SkypeRepositoryFolders.KontaktsucheFolder(this);
                _detailbereich = new TA_SkypeRepositoryFolders.DetailbereichFolder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d5da8c9-94d8-434d-a729-46b7cfac64f4")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d5da8c9-94d8-434d-a729-46b7cfac64f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titelzeile folder.
            /// </summary>
            [RepositoryFolder("10c8a60b-4d80-4cbe-bb10-e14950e0ec8f")]
            public virtual TA_SkypeRepositoryFolders.TitelzeileFolder Titelzeile
            {
                get { return _titelzeile; }
            }

            /// <summary>
            /// The Kontaktsuche folder.
            /// </summary>
            [RepositoryFolder("e8fc8a73-09ff-4854-b3e0-ad7ea304e7d9")]
            public virtual TA_SkypeRepositoryFolders.KontaktsucheFolder Kontaktsuche
            {
                get { return _kontaktsuche; }
            }

            /// <summary>
            /// The Detailbereich folder.
            /// </summary>
            [RepositoryFolder("9438d7d2-c5d3-4f32-959f-a04bc253d4ad")]
            public virtual TA_SkypeRepositoryFolders.DetailbereichFolder1 Detailbereich
            {
                get { return _detailbereich; }
            }
        }

        /// <summary>
        /// The TitelzeileFolder folder.
        /// </summary>
        [RepositoryFolder("10c8a60b-4d80-4cbe-bb10-e14950e0ec8f")]
        public partial class TitelzeileFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnschliessenInfo;
            RepoItemInfo _lbltitelInfo;

            /// <summary>
            /// Creates a new Titelzeile  folder.
            /// </summary>
            public TitelzeileFolder(RepoGenBaseFolder parentFolder) :
                    base("Titelzeile", "container[1]", parentFolder, 30000, null, false, "10c8a60b-4d80-4cbe-bb10-e14950e0ec8f", "")
            {
                _btnschliessenInfo = new RepoItemInfo(this, "btnSchliessen", "button[@name='Schließen']", 30000, null, "042561ce-0c01-43e2-9c38-92c374bb0118");
                _lbltitelInfo = new RepoItemInfo(this, "lblTitel", "text[@name='Neuen Kontakt hinzufügen']", 30000, null, "88dde387-34ba-4562-88c0-903028cb362e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10c8a60b-4d80-4cbe-bb10-e14950e0ec8f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10c8a60b-4d80-4cbe-bb10-e14950e0ec8f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnSchliessen item.
            /// </summary>
            [RepositoryItem("042561ce-0c01-43e2-9c38-92c374bb0118")]
            public virtual Ranorex.Button btnSchliessen
            {
                get
                {
                    return _btnschliessenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSchliessen item info.
            /// </summary>
            [RepositoryItemInfo("042561ce-0c01-43e2-9c38-92c374bb0118")]
            public virtual RepoItemInfo btnSchliessenInfo
            {
                get
                {
                    return _btnschliessenInfo;
                }
            }

            /// <summary>
            /// The lblTitel item.
            /// </summary>
            [RepositoryItem("88dde387-34ba-4562-88c0-903028cb362e")]
            public virtual Ranorex.Text lblTitel
            {
                get
                {
                    return _lbltitelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lblTitel item info.
            /// </summary>
            [RepositoryItemInfo("88dde387-34ba-4562-88c0-903028cb362e")]
            public virtual RepoItemInfo lblTitelInfo
            {
                get
                {
                    return _lbltitelInfo;
                }
            }
        }

        /// <summary>
        /// The KontaktsucheFolder folder.
        /// </summary>
        [RepositoryFolder("e8fc8a73-09ff-4854-b3e0-ad7ea304e7d9")]
        public partial class KontaktsucheFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnsucheschliessenInfo;
            RepoItemInfo _txtkontaktesuchenInfo;

            /// <summary>
            /// Creates a new Kontaktsuche  folder.
            /// </summary>
            public KontaktsucheFolder(RepoGenBaseFolder parentFolder) :
                    base("Kontaktsuche", "container[2]", parentFolder, 30000, null, false, "e8fc8a73-09ff-4854-b3e0-ad7ea304e7d9", "")
            {
                _btnsucheschliessenInfo = new RepoItemInfo(this, "btnSucheSchliessen", "button[@name='Suche schließen']", 30000, null, "b8e35b13-ca10-4574-b7d9-49a28236d978");
                _txtkontaktesuchenInfo = new RepoItemInfo(this, "txtKontakteSuchen", "container[@name='Kontakte suchen']/?/?/text[@classname='TextBox']", 30000, null, "fa7f6a40-fe51-4ca7-80c5-da41a5684a7e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e8fc8a73-09ff-4854-b3e0-ad7ea304e7d9")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e8fc8a73-09ff-4854-b3e0-ad7ea304e7d9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnSucheSchliessen item.
            /// </summary>
            [RepositoryItem("b8e35b13-ca10-4574-b7d9-49a28236d978")]
            public virtual Ranorex.Button btnSucheSchliessen
            {
                get
                {
                    return _btnsucheschliessenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSucheSchliessen item info.
            /// </summary>
            [RepositoryItemInfo("b8e35b13-ca10-4574-b7d9-49a28236d978")]
            public virtual RepoItemInfo btnSucheSchliessenInfo
            {
                get
                {
                    return _btnsucheschliessenInfo;
                }
            }

            /// <summary>
            /// The txtKontakteSuchen item.
            /// </summary>
            [RepositoryItem("fa7f6a40-fe51-4ca7-80c5-da41a5684a7e")]
            public virtual Ranorex.Text txtKontakteSuchen
            {
                get
                {
                    return _txtkontaktesuchenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtKontakteSuchen item info.
            /// </summary>
            [RepositoryItemInfo("fa7f6a40-fe51-4ca7-80c5-da41a5684a7e")]
            public virtual RepoItemInfo txtKontakteSuchenInfo
            {
                get
                {
                    return _txtkontaktesuchenInfo;
                }
            }
        }

        /// <summary>
        /// The DetailbereichFolder1 folder.
        /// </summary>
        [RepositoryFolder("9438d7d2-c5d3-4f32-959f-a04bc253d4ad")]
        public partial class DetailbereichFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _listitemeinladungInfo;
            RepoItemInfo _listitemtelefonnummerhinzufuegenInfo;

            /// <summary>
            /// Creates a new Detailbereich  folder.
            /// </summary>
            public DetailbereichFolder1(RepoGenBaseFolder parentFolder) :
                    base("Detailbereich", "container[@classname='ScrollViewer']/container[@orientation='None']", parentFolder, 30000, null, false, "9438d7d2-c5d3-4f32-959f-a04bc253d4ad", "")
            {
                _listitemeinladungInfo = new RepoItemInfo(this, "ListItemEinladung", "?/?/listitem[@text~'^Zu\\ Skype\\ einladen,\\ Lade\\ F' and @orientation='None' and @iscontentelement='True']", 30000, null, "74da48b8-c270-4521-98a7-bef9ccae8f72");
                _listitemtelefonnummerhinzufuegenInfo = new RepoItemInfo(this, "ListItemTelefonnummerHinzufuegen", "?/?/listitem[@name~'^Telefonnummer\\ hinzufügen,']", 30000, null, "b2a9b8f2-6748-4dee-9996-e39b7dce5db6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9438d7d2-c5d3-4f32-959f-a04bc253d4ad")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9438d7d2-c5d3-4f32-959f-a04bc253d4ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItemEinladung item.
            /// </summary>
            [RepositoryItem("74da48b8-c270-4521-98a7-bef9ccae8f72")]
            public virtual Ranorex.ListItem ListItemEinladung
            {
                get
                {
                    return _listitemeinladungInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemEinladung item info.
            /// </summary>
            [RepositoryItemInfo("74da48b8-c270-4521-98a7-bef9ccae8f72")]
            public virtual RepoItemInfo ListItemEinladungInfo
            {
                get
                {
                    return _listitemeinladungInfo;
                }
            }

            /// <summary>
            /// The ListItemTelefonnummerHinzufuegen item.
            /// </summary>
            [RepositoryItem("b2a9b8f2-6748-4dee-9996-e39b7dce5db6")]
            public virtual Ranorex.ListItem ListItemTelefonnummerHinzufuegen
            {
                get
                {
                    return _listitemtelefonnummerhinzufuegenInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTelefonnummerHinzufuegen item info.
            /// </summary>
            [RepositoryItemInfo("b2a9b8f2-6748-4dee-9996-e39b7dce5db6")]
            public virtual RepoItemInfo ListItemTelefonnummerHinzufuegenInfo
            {
                get
                {
                    return _listitemtelefonnummerhinzufuegenInfo;
                }
            }
        }

        /// <summary>
        /// The FrmTelefonnummerHinzufuegenFolder folder.
        /// </summary>
        [RepositoryFolder("2f0a9e0f-3d65-4078-a666-d33c67eca43b")]
        public partial class FrmTelefonnummerHinzufuegenFolder : RepoGenBaseFolder
        {
            TA_SkypeRepositoryFolders.TitelzeileFolder1 _titelzeile;
            TA_SkypeRepositoryFolders.DetailbereichFolder2 _detailbereich;

            /// <summary>
            /// Creates a new frmTelefonnummerHinzufuegen  folder.
            /// </summary>
            public FrmTelefonnummerHinzufuegenFolder(RepoGenBaseFolder parentFolder) :
                    base("frmTelefonnummerHinzufuegen", "container[6]/container[@name='Telefonnummer hinzufügen']/container[@orientation='None']", parentFolder, 30000, null, false, "2f0a9e0f-3d65-4078-a666-d33c67eca43b", "")
            {
                _titelzeile = new TA_SkypeRepositoryFolders.TitelzeileFolder1(this);
                _detailbereich = new TA_SkypeRepositoryFolders.DetailbereichFolder2(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f0a9e0f-3d65-4078-a666-d33c67eca43b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f0a9e0f-3d65-4078-a666-d33c67eca43b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titelzeile folder.
            /// </summary>
            [RepositoryFolder("49a439df-44e9-4f57-acb8-947d32f4dfec")]
            public virtual TA_SkypeRepositoryFolders.TitelzeileFolder1 Titelzeile
            {
                get { return _titelzeile; }
            }

            /// <summary>
            /// The Detailbereich folder.
            /// </summary>
            [RepositoryFolder("51dbd103-03b4-4b27-a49d-67344ea1f4b1")]
            public virtual TA_SkypeRepositoryFolders.DetailbereichFolder2 Detailbereich
            {
                get { return _detailbereich; }
            }
        }

        /// <summary>
        /// The TitelzeileFolder1 folder.
        /// </summary>
        [RepositoryFolder("49a439df-44e9-4f57-acb8-947d32f4dfec")]
        public partial class TitelzeileFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _btnzurueckInfo;
            RepoItemInfo _txttelefonnummerhinzufuegenInfo;
            RepoItemInfo _btnspeichernInfo;

            /// <summary>
            /// Creates a new Titelzeile  folder.
            /// </summary>
            public TitelzeileFolder1(RepoGenBaseFolder parentFolder) :
                    base("Titelzeile", "container[1]", parentFolder, 30000, null, false, "49a439df-44e9-4f57-acb8-947d32f4dfec", "")
            {
                _btnzurueckInfo = new RepoItemInfo(this, "btnZurueck", "button[@name='Zurück']", 30000, null, "31e951f5-1321-44c6-8de9-7bb039a68517");
                _txttelefonnummerhinzufuegenInfo = new RepoItemInfo(this, "txtTelefonnummerHinzufuegen", "text[@name='Telefonnummer hinzufügen']", 30000, null, "ac4dbfef-ce72-4157-9c5b-d05b9c0b7b2f");
                _btnspeichernInfo = new RepoItemInfo(this, "btnSpeichern", "button[@name='Speichern']", 30000, null, "d51edf63-4aa3-4867-8d02-1dc7c4579b56");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49a439df-44e9-4f57-acb8-947d32f4dfec")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49a439df-44e9-4f57-acb8-947d32f4dfec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnZurueck item.
            /// </summary>
            [RepositoryItem("31e951f5-1321-44c6-8de9-7bb039a68517")]
            public virtual Ranorex.Button btnZurueck
            {
                get
                {
                    return _btnzurueckInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnZurueck item info.
            /// </summary>
            [RepositoryItemInfo("31e951f5-1321-44c6-8de9-7bb039a68517")]
            public virtual RepoItemInfo btnZurueckInfo
            {
                get
                {
                    return _btnzurueckInfo;
                }
            }

            /// <summary>
            /// The txtTelefonnummerHinzufuegen item.
            /// </summary>
            [RepositoryItem("ac4dbfef-ce72-4157-9c5b-d05b9c0b7b2f")]
            public virtual Ranorex.Text txtTelefonnummerHinzufuegen
            {
                get
                {
                    return _txttelefonnummerhinzufuegenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTelefonnummerHinzufuegen item info.
            /// </summary>
            [RepositoryItemInfo("ac4dbfef-ce72-4157-9c5b-d05b9c0b7b2f")]
            public virtual RepoItemInfo txtTelefonnummerHinzufuegenInfo
            {
                get
                {
                    return _txttelefonnummerhinzufuegenInfo;
                }
            }

            /// <summary>
            /// The btnSpeichern item.
            /// </summary>
            [RepositoryItem("d51edf63-4aa3-4867-8d02-1dc7c4579b56")]
            public virtual Ranorex.Button btnSpeichern
            {
                get
                {
                    return _btnspeichernInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSpeichern item info.
            /// </summary>
            [RepositoryItemInfo("d51edf63-4aa3-4867-8d02-1dc7c4579b56")]
            public virtual RepoItemInfo btnSpeichernInfo
            {
                get
                {
                    return _btnspeichernInfo;
                }
            }
        }

        /// <summary>
        /// The DetailbereichFolder2 folder.
        /// </summary>
        [RepositoryFolder("51dbd103-03b4-4b27-a49d-67344ea1f4b1")]
        public partial class DetailbereichFolder2 : RepoGenBaseFolder
        {
            RepoItemInfo _txtvornameundnameInfo;
            RepoItemInfo _txttelefonnummerInfo;
            RepoItemInfo _btnlaendervorwahlInfo;
            RepoItemInfo _txtlaendervorwahlInfo;
            RepoItemInfo _btntelefonnummertypInfo;
            RepoItemInfo _txttelefonnummertypInfo;

            /// <summary>
            /// Creates a new Detailbereich  folder.
            /// </summary>
            public DetailbereichFolder2(RepoGenBaseFolder parentFolder) :
                    base("Detailbereich", "container/container[@classname='ScrollViewer']/container[@orientation='None']", parentFolder, 30000, null, false, "51dbd103-03b4-4b27-a49d-67344ea1f4b1", "")
            {
                _txtvornameundnameInfo = new RepoItemInfo(this, "txtVornameUndName", "?/listitem[@name='Vor- und Nachname']//text", 30000, null, "8e5091a1-3056-4eb9-b96b-632824ce9790");
                _txttelefonnummerInfo = new RepoItemInfo(this, "txtTelefonnummer", "?/listitem[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']//text", 30000, null, "d7055de0-22a6-4729-9ba6-91bbf2cb168d");
                _btnlaendervorwahlInfo = new RepoItemInfo(this, "btnLaendervorwahl", "?/listitem[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']//button[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']", 30000, null, "f0eb7897-7c74-4236-bff8-9b8248c1b9aa");
                _txtlaendervorwahlInfo = new RepoItemInfo(this, "txtLaendervorwahl", "?/listitem[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']//button[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']/container/container/text", 30000, null, "ae85308c-686b-47ee-87e4-ecb994cb5a7f");
                _btntelefonnummertypInfo = new RepoItemInfo(this, "btnTelefonnummerTyp", "?/listitem[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']//button[2]", 30000, null, "fda8ac53-aee5-4bda-9a22-e2e03688f029");
                _txttelefonnummertypInfo = new RepoItemInfo(this, "txtTelefonnummerTyp", "?/listitem[@name~'^Anrufcode\\ für\\ Länder\\ und\\ ']//button[2]/container/container/text", 30000, null, "a3b3bb83-0d16-47ec-9551-f4cfef310d6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51dbd103-03b4-4b27-a49d-67344ea1f4b1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51dbd103-03b4-4b27-a49d-67344ea1f4b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtVornameUndName item.
            /// </summary>
            [RepositoryItem("8e5091a1-3056-4eb9-b96b-632824ce9790")]
            public virtual Ranorex.Text txtVornameUndName
            {
                get
                {
                    return _txtvornameundnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtVornameUndName item info.
            /// </summary>
            [RepositoryItemInfo("8e5091a1-3056-4eb9-b96b-632824ce9790")]
            public virtual RepoItemInfo txtVornameUndNameInfo
            {
                get
                {
                    return _txtvornameundnameInfo;
                }
            }

            /// <summary>
            /// The txtTelefonnummer item.
            /// </summary>
            [RepositoryItem("d7055de0-22a6-4729-9ba6-91bbf2cb168d")]
            public virtual Ranorex.Text txtTelefonnummer
            {
                get
                {
                    return _txttelefonnummerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTelefonnummer item info.
            /// </summary>
            [RepositoryItemInfo("d7055de0-22a6-4729-9ba6-91bbf2cb168d")]
            public virtual RepoItemInfo txtTelefonnummerInfo
            {
                get
                {
                    return _txttelefonnummerInfo;
                }
            }

            /// <summary>
            /// The btnLaendervorwahl item.
            /// </summary>
            [RepositoryItem("f0eb7897-7c74-4236-bff8-9b8248c1b9aa")]
            public virtual Ranorex.Button btnLaendervorwahl
            {
                get
                {
                    return _btnlaendervorwahlInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLaendervorwahl item info.
            /// </summary>
            [RepositoryItemInfo("f0eb7897-7c74-4236-bff8-9b8248c1b9aa")]
            public virtual RepoItemInfo btnLaendervorwahlInfo
            {
                get
                {
                    return _btnlaendervorwahlInfo;
                }
            }

            /// <summary>
            /// The txtLaendervorwahl item.
            /// </summary>
            [RepositoryItem("ae85308c-686b-47ee-87e4-ecb994cb5a7f")]
            public virtual Ranorex.Text txtLaendervorwahl
            {
                get
                {
                    return _txtlaendervorwahlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtLaendervorwahl item info.
            /// </summary>
            [RepositoryItemInfo("ae85308c-686b-47ee-87e4-ecb994cb5a7f")]
            public virtual RepoItemInfo txtLaendervorwahlInfo
            {
                get
                {
                    return _txtlaendervorwahlInfo;
                }
            }

            /// <summary>
            /// The btnTelefonnummerTyp item.
            /// </summary>
            [RepositoryItem("fda8ac53-aee5-4bda-9a22-e2e03688f029")]
            public virtual Ranorex.Button btnTelefonnummerTyp
            {
                get
                {
                    return _btntelefonnummertypInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnTelefonnummerTyp item info.
            /// </summary>
            [RepositoryItemInfo("fda8ac53-aee5-4bda-9a22-e2e03688f029")]
            public virtual RepoItemInfo btnTelefonnummerTypInfo
            {
                get
                {
                    return _btntelefonnummertypInfo;
                }
            }

            /// <summary>
            /// The txtTelefonnummerTyp item.
            /// </summary>
            [RepositoryItem("a3b3bb83-0d16-47ec-9551-f4cfef310d6a")]
            public virtual Ranorex.Text txtTelefonnummerTyp
            {
                get
                {
                    return _txttelefonnummertypInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtTelefonnummerTyp item info.
            /// </summary>
            [RepositoryItemInfo("a3b3bb83-0d16-47ec-9551-f4cfef310d6a")]
            public virtual RepoItemInfo txtTelefonnummerTypInfo
            {
                get
                {
                    return _txttelefonnummertypInfo;
                }
            }
        }

        /// <summary>
        /// The FrmLaendervorwahlFolder folder.
        /// </summary>
        [RepositoryFolder("601baf19-5e57-496d-80f6-7dd89fb4fd2e")]
        public partial class FrmLaendervorwahlFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtlandregionsuchenInfo;
            RepoItemInfo _listitemlaendervorwahlInfo;

            /// <summary>
            /// Creates a new frmLaendervorwahl  folder.
            /// </summary>
            public FrmLaendervorwahlFolder(RepoGenBaseFolder parentFolder) :
                    base("frmLaendervorwahl", "element[@orientation='None']//container[@classname='NamedContainerAutomationPeer']/following-sibling::container", parentFolder, 30000, null, false, "601baf19-5e57-496d-80f6-7dd89fb4fd2e", "")
            {
                _txtlandregionsuchenInfo = new RepoItemInfo(this, "txtLandRegionSuchen", "container[@name='Land/Region suchen']/?/?/text[@classname='TextBox']/text", 30000, null, "8096e225-167f-4d94-852a-faa311ec5163");
                _listitemlaendervorwahlInfo = new RepoItemInfo(this, "ListItemLaendervorwahl", "container[@classname='ScrollViewer']/?/?/listitem[@name=$Land+' '+$Laendervorwahl]", 30000, null, "a854ca3e-cb15-4e70-b937-5447eea38f9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("601baf19-5e57-496d-80f6-7dd89fb4fd2e")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("601baf19-5e57-496d-80f6-7dd89fb4fd2e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtLandRegionSuchen item.
            /// </summary>
            [RepositoryItem("8096e225-167f-4d94-852a-faa311ec5163")]
            public virtual Ranorex.Text txtLandRegionSuchen
            {
                get
                {
                    return _txtlandregionsuchenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtLandRegionSuchen item info.
            /// </summary>
            [RepositoryItemInfo("8096e225-167f-4d94-852a-faa311ec5163")]
            public virtual RepoItemInfo txtLandRegionSuchenInfo
            {
                get
                {
                    return _txtlandregionsuchenInfo;
                }
            }

            /// <summary>
            /// The ListItemLaendervorwahl item.
            /// </summary>
            [RepositoryItem("a854ca3e-cb15-4e70-b937-5447eea38f9d")]
            public virtual Ranorex.ListItem ListItemLaendervorwahl
            {
                get
                {
                    return _listitemlaendervorwahlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemLaendervorwahl item info.
            /// </summary>
            [RepositoryItemInfo("a854ca3e-cb15-4e70-b937-5447eea38f9d")]
            public virtual RepoItemInfo ListItemLaendervorwahlInfo
            {
                get
                {
                    return _listitemlaendervorwahlInfo;
                }
            }
        }

        /// <summary>
        /// The None1Folder folder.
        /// </summary>
        [RepositoryFolder("62fa1213-ccc6-451a-9235-71d577eca75a")]
        public partial class None1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _jaundanmeldedatenloeschenInfo;
            RepoItemInfo _loginfeld_emailadresseInfo;
            RepoItemInfo _loginfeld_passworteInfo;

            /// <summary>
            /// Creates a new None1  folder.
            /// </summary>
            public None1Folder(RepoGenBaseFolder parentFolder) :
                    base("None1", "element/container[@orientation='None']/container[@orientation='None']", parentFolder, 30000, null, false, "62fa1213-ccc6-451a-9235-71d577eca75a", "")
            {
                _jaundanmeldedatenloeschenInfo = new RepoItemInfo(this, "JaUndAnmeldedatenLoeschen", "container[2]/container[3]/container[@name~'^Möchtest\\ du\\ dich\\ wirklich']/?/?/button[@name~'^Ja,\\ und\\ Anmeldedaten\\ lösc']/?/?/text[@name~'^Ja,\\ und\\ Anmeldedaten\\ lösc']", 30000, null, "ac9d2d35-7e17-4644-9015-4c097cb85a00");
                _loginfeld_emailadresseInfo = new RepoItemInfo(this, "Loginfeld_Emailadresse", "container[3]/?/?/container[@name~'^https://login\\.live\\.com/oa']/container[@name='Bei Skype anmelden']/container[@automationid='i0281']/?/?/text[@automationid='i0116']", 30000, null, "55b48a56-3677-451a-8f19-02eef2337ce4");
                _loginfeld_passworteInfo = new RepoItemInfo(this, "Loginfeld_Passworte", "container[3]/?/?/container[@name~'^https://login\\.live\\.com/oa']/container[@name='Bei Skype anmelden']/container[@automationid='i0281']/?/?/text[@automationid='i0118']", 30000, null, "e64b8548-479e-4390-827a-e8f8f160e30c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("62fa1213-ccc6-451a-9235-71d577eca75a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("62fa1213-ccc6-451a-9235-71d577eca75a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JaUndAnmeldedatenLoeschen item.
            /// </summary>
            [RepositoryItem("ac9d2d35-7e17-4644-9015-4c097cb85a00")]
            public virtual Ranorex.Text JaUndAnmeldedatenLoeschen
            {
                get
                {
                    return _jaundanmeldedatenloeschenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The JaUndAnmeldedatenLoeschen item info.
            /// </summary>
            [RepositoryItemInfo("ac9d2d35-7e17-4644-9015-4c097cb85a00")]
            public virtual RepoItemInfo JaUndAnmeldedatenLoeschenInfo
            {
                get
                {
                    return _jaundanmeldedatenloeschenInfo;
                }
            }

            /// <summary>
            /// The Loginfeld_Emailadresse item.
            /// </summary>
            [RepositoryItem("55b48a56-3677-451a-8f19-02eef2337ce4")]
            public virtual Ranorex.Text Loginfeld_Emailadresse
            {
                get
                {
                    return _loginfeld_emailadresseInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Loginfeld_Emailadresse item info.
            /// </summary>
            [RepositoryItemInfo("55b48a56-3677-451a-8f19-02eef2337ce4")]
            public virtual RepoItemInfo Loginfeld_EmailadresseInfo
            {
                get
                {
                    return _loginfeld_emailadresseInfo;
                }
            }

            /// <summary>
            /// The Loginfeld_Passworte item.
            /// </summary>
            [RepositoryItem("e64b8548-479e-4390-827a-e8f8f160e30c")]
            public virtual Ranorex.Text Loginfeld_Passworte
            {
                get
                {
                    return _loginfeld_passworteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Loginfeld_Passworte item info.
            /// </summary>
            [RepositoryItemInfo("e64b8548-479e-4390-827a-e8f8f160e30c")]
            public virtual RepoItemInfo Loginfeld_PassworteInfo
            {
                get
                {
                    return _loginfeld_passworteInfo;
                }
            }
        }

        /// <summary>
        /// The PopupMenuFolder folder.
        /// </summary>
        [RepositoryFolder("8805602d-800e-4666-b193-10151d283d95")]
        public partial class PopupMenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemeinstellungenInfo;
            RepoItemInfo _itemabmeldenInfo;
            RepoItemInfo _itemtelefonnummertypInfo;

            /// <summary>
            /// Creates a new PopupMenu  folder.
            /// </summary>
            public PopupMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("PopupMenu", "form[@name='Popup']", parentFolder, 30000, null, false, "8805602d-800e-4666-b193-10151d283d95", "")
            {
                _itemeinstellungenInfo = new RepoItemInfo(this, "ItemEinstellungen", ".//text[@name='Einstellungen']", 30000, null, "75e4319d-71ea-4037-ba9e-837b56213ef2");
                _itemabmeldenInfo = new RepoItemInfo(this, "ItemAbmelden", ".//text[@name='Abmelden']", 30000, null, "af79c8cc-bc67-4a90-b82f-fafcdcdad07a");
                _itemtelefonnummertypInfo = new RepoItemInfo(this, "ItemTelefonnummerTyp", ".//text[@name=$TelefonnummerTyp]", 30000, null, "a354cecb-9f0c-472b-a171-beb730b4f3b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8805602d-800e-4666-b193-10151d283d95")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8805602d-800e-4666-b193-10151d283d95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ItemEinstellungen item.
            /// </summary>
            [RepositoryItem("75e4319d-71ea-4037-ba9e-837b56213ef2")]
            public virtual Ranorex.Text ItemEinstellungen
            {
                get
                {
                    return _itemeinstellungenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ItemEinstellungen item info.
            /// </summary>
            [RepositoryItemInfo("75e4319d-71ea-4037-ba9e-837b56213ef2")]
            public virtual RepoItemInfo ItemEinstellungenInfo
            {
                get
                {
                    return _itemeinstellungenInfo;
                }
            }

            /// <summary>
            /// The ItemAbmelden item.
            /// </summary>
            [RepositoryItem("af79c8cc-bc67-4a90-b82f-fafcdcdad07a")]
            public virtual Ranorex.Text ItemAbmelden
            {
                get
                {
                    return _itemabmeldenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ItemAbmelden item info.
            /// </summary>
            [RepositoryItemInfo("af79c8cc-bc67-4a90-b82f-fafcdcdad07a")]
            public virtual RepoItemInfo ItemAbmeldenInfo
            {
                get
                {
                    return _itemabmeldenInfo;
                }
            }

            /// <summary>
            /// The ItemTelefonnummerTyp item.
            /// </summary>
            [RepositoryItem("a354cecb-9f0c-472b-a171-beb730b4f3b6")]
            public virtual Ranorex.Text ItemTelefonnummerTyp
            {
                get
                {
                    return _itemtelefonnummertypInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ItemTelefonnummerTyp item info.
            /// </summary>
            [RepositoryItemInfo("a354cecb-9f0c-472b-a171-beb730b4f3b6")]
            public virtual RepoItemInfo ItemTelefonnummerTypInfo
            {
                get
                {
                    return _itemtelefonnummertypInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}