///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Testchat_TestAutomation_DialogLoeschen recording.
    /// </summary>
    [TestModule("2af4ab27-dd76-435b-8113-e8b7e8060627", ModuleType.Recording, 1)]
    public partial class Testchat_TestAutomation_DialogLoeschen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static Testchat_TestAutomation_DialogLoeschen instance = new Testchat_TestAutomation_DialogLoeschen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Testchat_TestAutomation_DialogLoeschen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Testchat_TestAutomation_DialogLoeschen Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable VornameUndName.
        /// </summary>
        [TestVariable("c880ee55-32ec-4543-be01-a612266cf2bc")]
        public string VornameUndName
        {
            get { return repo.VornameUndName; }
            set { repo.VornameUndName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUser'.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUserInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUserInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUser' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUserInfo, new RecordItemIndex(1));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ListItemChatUser.Click(System.Windows.Forms.MouseButtons.Right);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.PopupMenu.MenuItemUnterhaltungLoeschen'.", repo.Skype.PopupMenu.MenuItemUnterhaltungLoeschenInfo, new RecordItemIndex(2));
            Validate.Exists(repo.Skype.PopupMenu.MenuItemUnterhaltungLoeschenInfo);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.PopupMenu.MenuItemUnterhaltungLoeschen' at Center.", repo.Skype.PopupMenu.MenuItemUnterhaltungLoeschenInfo, new RecordItemIndex(4));
            repo.Skype.PopupMenu.MenuItemUnterhaltungLoeschen.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.PopupWindow'.", repo.Skype.PopupWindow.SelfInfo, new RecordItemIndex(5));
            Validate.Exists(repo.Skype.PopupWindow.SelfInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.PopupWindow.btnLoeschen' at Center.", repo.Skype.PopupWindow.btnLoeschenInfo, new RecordItemIndex(6));
            repo.Skype.PopupWindow.btnLoeschen.Click();
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Skype.PopupMenu.MenuItemAusFavoritenEntfernen'.", repo.Skype.PopupMenu.MenuItemAusFavoritenEntfernenInfo, new RecordItemIndex(7));
            //Validate.Exists(repo.Skype.PopupMenu.MenuItemAusFavoritenEntfernenInfo);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.PopupMenu.MenuItemAusFavoritenEntfernen' at Center.", repo.Skype.PopupMenu.MenuItemAusFavoritenEntfernenInfo, new RecordItemIndex(8));
            //repo.Skype.PopupMenu.MenuItemAusFavoritenEntfernen.Click();
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(9));
            //Keyboard.Press("{Return}");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
