///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TA_Skype
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Testchat_TestAutomation_DialogLoeschen recording.
    /// </summary>
    [TestModule("2af4ab27-dd76-435b-8113-e8b7e8060627", ModuleType.Recording, 1)]
    public partial class Testchat_TestAutomation_DialogLoeschen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TA_SkypeRepository repository.
        /// </summary>
        public static TA_SkypeRepository repo = TA_SkypeRepository.Instance;

        static Testchat_TestAutomation_DialogLoeschen instance = new Testchat_TestAutomation_DialogLoeschen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Testchat_TestAutomation_DialogLoeschen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Testchat_TestAutomation_DialogLoeschen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.SarahPfister' at 59;10.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.SarahPfisterInfo, new RecordItemIndex(0));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.SarahPfister.Click("59;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.Chatfenster' at Center.", repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.ChatfensterInfo, new RecordItemIndex(1));
            repo.Skype.frmSkypeMain.frmSkypeMainAreaLinks.Detailbereich.Chatfenster.Click(System.Windows.Forms.MouseButtons.Right);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Skype.UnterhaltungLoeschen' at 88;13.", repo.Skype.UnterhaltungLoeschenInfo, new RecordItemIndex(2));
            repo.Skype.UnterhaltungLoeschen.Click("88;13");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Return}");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
